"use server";
import { and, eq, inArray } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requirePermission } from "@/src/auth/authorization";
import { db } from "@/src/db";
import { activityLogs, adminNotifications } from "@/src/db/schema";
import { visibleNotificationModules } from "@/src/notifications/service";

const idSchema = z.uuid();
export async function markAllNotificationsRead() { const { session, authorization } = await requirePermission("notifications.manage"), modules = visibleNotificationModules(authorization); if (!modules.length) return; const now = new Date(), changed = await db.update(adminNotifications).set({ status: "read", readAt: now }).where(and(eq(adminNotifications.status, "unread"), inArray(adminNotifications.module, modules))).returning({ id: adminNotifications.id }); if (changed.length) await db.insert(activityLogs).values({ staffAccountId: session.user.id, action: "notification.all_read", entityType: "admin_notification", description: "Accessible operational notifications marked read.", metadata: { count: changed.length } }); revalidatePath("/notifications"); }
export async function markNotificationReadAction(formData:FormData){const parsed=idSchema.safeParse(formData.get("notificationId"));if(!parsed.success)throw new Error("Invalid notification.");const{session,authorization}=await requirePermission("notifications.manage"),modules=visibleNotificationModules(authorization);if(!modules.length)throw new Error("Notification is unavailable.");const now=new Date(),[changed]=await db.update(adminNotifications).set({status:"read",readAt:now}).where(and(eq(adminNotifications.id,parsed.data),eq(adminNotifications.status,"unread"),inArray(adminNotifications.module,modules))).returning({id:adminNotifications.id});if(changed)await db.insert(activityLogs).values({staffAccountId:session.user.id,action:"notification.read",entityType:"admin_notification",entityId:changed.id,description:"Operational notification read."});revalidatePath("/notifications");}
export async function resolveNotification(formData: FormData) { const parsed=idSchema.safeParse(formData.get("notificationId")); if(!parsed.success) throw new Error("Invalid notification."); const {session,authorization}=await requirePermission("notifications.manage"),modules=visibleNotificationModules(authorization); if(!modules.length) throw new Error("Notification is unavailable."); const now=new Date(),[changed]=await db.update(adminNotifications).set({status:"resolved",readAt:now,resolvedAt:now}).where(and(eq(adminNotifications.id,parsed.data),inArray(adminNotifications.module,modules))).returning({id:adminNotifications.id}); if(!changed) throw new Error("Notification is unavailable."); await db.insert(activityLogs).values({staffAccountId:session.user.id,action:"notification.resolved",entityType:"admin_notification",entityId:changed.id,description:"Operational notification resolved."}); revalidatePath("/notifications"); }
