"use client";
import Image from "next/image";
import { useActionState, useState } from "react";
import { saveHeader } from "@/app/(admin)/header/actions";
import { uploadImage } from "@/components/image-upload";
import type { HeaderConfig } from "@/src/header/config";

export type HeaderPageOption = { id: string; title: string; path: string };
type Item = HeaderConfig["manualItems"][number];
export function HeaderForm({ config, pageOptions, version, canEdit, canPublish, result }: { config: HeaderConfig; pageOptions: HeaderPageOption[]; version: number; canEdit: boolean; canPublish: boolean; result?: string }) {
  const [state, action, pending] = useActionState(saveHeader, {}); const [logo, setLogo] = useState(config.branding.logoPath); const [mode, setMode] = useState(config.branding.mode); const [items, setItems] = useState(config.manualItems); const [order, setOrder] = useState(config.defaults.order); const disabled=!canEdit||pending;
  const moveDefaults=(index:number,delta:number)=>setOrder(current=>{const target=index+delta;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next;});
  const patch=(pageId:string,value:Partial<Item>)=>setItems(all=>all.map(item=>item.pageId===pageId?{...item,...value}:item));
  const moveItem=(index:number,delta:number)=>setItems(current=>{const target=index+delta;if(target<0||target>=current.length||current[target].parentPageId!==current[index].parentPageId)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next.map((item,order)=>({...item,order}));});
  const available=pageOptions.filter(page=>!items.some(item=>item.pageId===page.id)); const topLevel=items.filter(item=>!item.parentPageId&&item.visible);
  return <section className="home-cms-page"><div className="page-heading"><p className="page-eyebrow">Universal site chrome</p><h1>Header</h1><p>Edit the Draft independently, then publish it atomically across every public page.</p></div>{result?<p className="success-message">Header {result==="publish"?"published":"Draft saved"}.</p>:null}<form className="home-cms-form" action={action}><input type="hidden" name="expectedVersion" value={version}/><input type="hidden" name="logoPath" value={logo}/><input type="hidden" name="manualItems" value={JSON.stringify(items)}/><input type="hidden" name="defaultOrder" value={JSON.stringify(order)}/>{state.error?<p className="form-error">{state.error}</p>:null}
  <section className="form-section"><div className="section-heading"><h2>Branding</h2><p>Choose one public branding mode. Both modes retain their Draft values when inactive.</p></div><fieldset><legend>Branding Type</legend><label><input type="radio" name="brandingMode" value="logo" checked={mode==="logo"} onChange={()=>setMode("logo")} disabled={disabled}/> Logo</label><label><input type="radio" name="brandingMode" value="text" checked={mode==="text"} onChange={()=>setMode("text")} disabled={disabled}/> Text Branding</label></fieldset>{mode==="logo"?<div>{logo?<Image src={logo} alt="Logo Draft preview" width={100} height={100} unoptimized/>:<div className="brand-initial" aria-label="Default E logo preview">E</div>}<label className="upload-control">{logo?"Replace logo":"Upload logo"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={disabled} onChange={async event=>{const file=event.target.files?.[0];if(file)setLogo(await uploadImage(file));}}/></label>{logo?<button type="button" onClick={()=>setLogo("")} disabled={disabled}>Remove logo</button>:null}<input type="hidden" name="line1" value={config.branding.line1}/><input type="hidden" name="line2" value={config.branding.line2}/></div>:<div><label>Brand Line 1<input name="line1" defaultValue={config.branding.line1} maxLength={80} disabled={disabled}/></label><label>Brand Line 2<input name="line2" defaultValue={config.branding.line2} maxLength={120} disabled={disabled}/></label></div>}</section>
  <section className="form-section"><div className="section-heading"><h2>Default Navigation</h2></div>{order.map((key,index)=><div className="menu-editor-row" key={key}><label><input type="checkbox" name={`${key}Visible`} defaultChecked={config.defaults[`${key}Visible` as keyof typeof config.defaults] as boolean} disabled={disabled}/> {key==="contact"?"Contact Us":key==="about"?"About Us":key[0].toUpperCase()+key.slice(1)}</label><button type="button" onClick={()=>moveDefaults(index,-1)} disabled={disabled||index===0}>Move Up</button><button type="button" onClick={()=>moveDefaults(index,1)} disabled={disabled||index===order.length-1}>Move Down</button></div>)}</section>
  <section className="form-section"><div className="section-heading"><h2>Page Navigation</h2><p>Page titles and paths are resolved from current eligible published Pages.</p></div>{pageOptions.length===0?<p className="public-empty">No Pages are available for Header navigation. Create and publish a Page first.</p>:<>{items.map((item,index)=>{const page=pageOptions.find(option=>option.id===item.pageId);return <div className="menu-item-editor" key={item.pageId}><strong>{page?.title??"Unavailable Page"}</strong><span>{page?.path??"Not publicly eligible"}</span><select aria-label={`Menu position for ${page?.title??"Page"}`} value={item.parentPageId?"child":"top"} onChange={event=>patch(item.pageId,{parentPageId:event.target.value==="top"?null:topLevel.find(candidate=>candidate.pageId!==item.pageId)?.pageId??null})} disabled={disabled}><option value="top">Top Level</option><option value="child" disabled={!topLevel.some(candidate=>candidate.pageId!==item.pageId)}>Child Menu Item</option></select>{item.parentPageId?<select aria-label="Parent Menu" value={item.parentPageId} onChange={event=>patch(item.pageId,{parentPageId:event.target.value})} disabled={disabled}>{topLevel.filter(candidate=>candidate.pageId!==item.pageId).map(candidate=><option key={candidate.pageId} value={candidate.pageId}>{pageOptions.find(option=>option.id===candidate.pageId)?.title}</option>)}</select>:null}<label><input type="checkbox" checked={item.visible} onChange={event=>patch(item.pageId,{visible:event.target.checked})} disabled={disabled}/> Visible</label><span><button type="button" onClick={()=>moveItem(index,-1)} disabled={disabled}>Move Up</button><button type="button" onClick={()=>moveItem(index,1)} disabled={disabled}>Move Down</button><button type="button" onClick={()=>setItems(all=>all.filter(entry=>entry.pageId!==item.pageId).map(entry=>entry.parentPageId===item.pageId?{...entry,parentPageId:null}:entry))} disabled={disabled}>Remove</button></span></div>})}{available.length?<label>Add Page Menu Item<select value="" onChange={event=>{const pageId=event.target.value;if(pageId)setItems(all=>[...all,{pageId,parentPageId:null,visible:true,order:all.length}]);}} disabled={disabled}><option value="">Select a published Page…</option>{available.map(page=><option key={page.id} value={page.id}>{page.title}</option>)}</select></label>:null}</>}</section>
  <section className="form-section"><div className="section-heading"><h2>Announcement</h2></div><label><input type="checkbox" name="announcementVisible" defaultChecked={config.announcement.visible} disabled={disabled}/> Visible on website</label><label>Message<input name="announcementMessage" defaultValue={config.announcement.message} maxLength={240} disabled={disabled}/></label></section><div className="home-cms-actions">{canEdit?<button name="intent" value="draft" disabled={pending}>Save Draft</button>:null}{canPublish?<button className="primary-action" name="intent" value="publish" disabled={pending}>Publish Changes</button>:null}</div></form></section>;
}
