"use client";
import { useActionState, useState } from "react";
import Image from "next/image";
import { saveHeader } from "@/app/(admin)/header/actions";
import { uploadImage } from "@/components/image-upload";
import type { HeaderConfig } from "@/src/header/config";
type Item = HeaderConfig["manualItems"][number];
export function HeaderForm({ config, version, canEdit, canPublish, result }: { config: HeaderConfig; version: number; canEdit: boolean; canPublish: boolean; result?: string }) {
  const [state, action, pending] = useActionState(saveHeader, {}); const [logo, setLogo] = useState(config.branding.logoPath); const [items, setItems] = useState(config.manualItems); const [order, setOrder] = useState(config.defaults.order); const disabled = !canEdit || pending;
  const patch = (id: string, value: Partial<Item>) => setItems((all) => all.map((item) => item.id === id ? { ...item, ...value } : item));
  const move = (index: number, delta: number) => setOrder((current) => { const next = [...current]; const target = index + delta; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next; }); const moveItem=(index:number,delta:number)=>setItems((current)=>{const target=index+delta;if(target<0||target>=current.length||current[target].parentId!==current[index].parentId)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next.map((item,order)=>({...item,order}));});
  return <section className="home-cms-page"><div className="page-heading"><p className="page-eyebrow">Universal site chrome</p><h1>Header</h1><p>Edit the Draft independently, then publish it atomically across every public page.</p></div>{result ? <p className="success-message">Header {result === "publish" ? "published" : "Draft saved"}.</p> : null}<form className="home-cms-form" action={action}><input type="hidden" name="expectedVersion" value={version}/><input type="hidden" name="logoPath" value={logo}/><input type="hidden" name="manualItems" value={JSON.stringify(items)}/><input type="hidden" name="defaultOrder" value={JSON.stringify(order)}/>{state.error ? <p className="form-error">{state.error}</p> : null}
  <section className="form-section"><div className="section-heading"><h2>Branding / Logo</h2><p>Without an uploaded image, the approved Eraasim initial mark remains.</p></div><label>Brand text line 1<input name="line1" defaultValue={config.branding.line1} disabled={disabled}/></label><label>Brand text line 2<input name="line2" defaultValue={config.branding.line2} disabled={disabled}/></label>{logo ? <Image src={logo} alt="Logo Draft preview" width={100} height={100} unoptimized/> : <div className="brand-initial">E</div>}<label className="upload-control">{logo ? "Replace logo" : "Upload logo"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={disabled} onChange={async (event) => { const file = event.target.files?.[0]; if (file) setLogo(await uploadImage(file)); }}/></label>{logo ? <button type="button" onClick={() => setLogo("")} disabled={disabled}>Remove logo</button> : null}</section>
  <section className="form-section"><div className="section-heading"><h2>Default menu</h2><p>Contact Us remains unresolved until a real route exists; it renders as non-link text.</p></div>{order.map((key, index) => <div className="menu-editor-row" key={key}><label><input type="checkbox" name={`${key}Visible`} defaultChecked={config.defaults[`${key}Visible` as "homeVisible"]} disabled={disabled}/> {key === "contact" ? "Contact Us" : key[0].toUpperCase() + key.slice(1)}</label><button type="button" onClick={() => move(index,-1)} disabled={disabled || index === 0}>Move Up</button><button type="button" onClick={() => move(index,1)} disabled={disabled || index === order.length-1}>Move Down</button></div>)}</section>
  <section className="form-section"><div className="section-heading"><h2>Manual menu items</h2><p>Controlled destinations support safe internal paths and HTTP(S). Maximum depth is two.</p></div>{items.map((item, index) => <div className="menu-item-editor" key={item.id}><input aria-label="Label" value={item.label} onChange={(e)=>patch(item.id,{label:e.target.value})} disabled={disabled}/><input aria-label="Destination" value={item.destination} onChange={(e)=>patch(item.id,{destination:e.target.value})} disabled={disabled}/><select aria-label="Parent Menu Item" value={item.parentId ?? ""} onChange={(e)=>patch(item.id,{parentId:e.target.value || null})} disabled={disabled}><option value="">Top level</option>{items.filter((candidate)=>candidate.id!==item.id && !candidate.parentId).map((candidate)=><option key={candidate.id} value={candidate.id}>{candidate.label}</option>)}</select><label><input type="checkbox" checked={item.visible} onChange={(e)=>patch(item.id,{visible:e.target.checked})}/> Visible</label><span><button type="button" onClick={()=>moveItem(index,-1)} disabled={disabled}>↑</button><button type="button" onClick={()=>moveItem(index,1)} disabled={disabled}>↓</button><button type="button" onClick={()=>setItems((all)=>all.filter((entry)=>entry.id!==item.id).map((entry)=>entry.parentId===item.id?{...entry,parentId:null}:entry))} disabled={disabled}>Remove</button></span></div>)}<button type="button" disabled={disabled || items.length>=30} onClick={()=>setItems((all)=>[...all,{id:crypto.randomUUID(),label:"New Item",destination:"/",parentId:null,visible:true,order:all.length}])}>Add menu item</button></section>
  <section className="form-section"><div className="section-heading"><h2>Announcement</h2></div><label><input type="checkbox" name="announcementVisible" defaultChecked={config.announcement.visible} disabled={disabled}/> Visible on website</label><label>Message<input name="announcementMessage" defaultValue={config.announcement.message} maxLength={240} disabled={disabled}/></label></section>
  <div className="home-cms-actions">{canEdit?<button name="intent" value="draft" disabled={pending}>Save Draft</button>:null}{canPublish?<button className="primary-action" name="intent" value="publish" disabled={pending}>Publish Changes</button>:null}</div></form></section>;
}
