"use client";
import { useActionState, useState } from "react";
import Image from "next/image";
import { saveHomePage, type HomeFormState } from "@/app/(admin)/pages/home/actions";
import { uploadImage } from "@/components/image-upload";
import { heroDestinations, heroSizeBounds, type HomeConfig, sectionIds } from "@/src/home-page/config";

const labels = { hero: "Hero", featuredStory: "Featured Story", latestStories: "Latest & Trending Stories" };
type PostOption = { id: string; title: string; categoryName: string | null; categoryId: string | null; categoryParentId: string | null };
function PostSelect({ name, value, posts, disabled }: { name: string; value?: string | null; posts: PostOption[]; disabled: boolean }) { const [query, setQuery] = useState(""); const selected = posts.find((post) => post.id === value); const visible = posts.filter((post) => !query || `${post.title} ${post.categoryName ?? "Uncategorized"}`.toLowerCase().includes(query.toLowerCase()) || post.id === value); return <span className="post-selector"><input type="search" placeholder="Filter by title or category" value={query} onChange={(event) => setQuery(event.target.value)} disabled={disabled} /><select name={name} defaultValue={value ?? ""} disabled={disabled}><option value="">Select a published post</option>{selected && !visible.includes(selected) ? <option value={selected.id}>{selected.title}</option> : null}{visible.map((post) => <option key={post.id} value={post.id}>{post.categoryName ? `${post.categoryName}${post.categoryParentId ? " · Child" : " · Parent"}` : "Uncategorized"} — {post.title}</option>)}</select></span>; }

function NumberStepper({ name, label, initial, bounds, disabled }: { name: string; label: string; initial: number; bounds: { min: number; max: number }; disabled: boolean }) {
  const [value, setValue] = useState(initial);
  const adjust = (amount: number) => setValue((current) => Math.min(bounds.max, Math.max(bounds.min, current + amount)));
  return <label>{label}<span className="number-stepper"><button type="button" aria-label={`Decrease ${label}`} onClick={() => adjust(-1)} disabled={disabled || value <= bounds.min}>−</button><input name={name} type="number" min={bounds.min} max={bounds.max} step={1} value={value} onChange={(event) => setValue(event.target.valueAsNumber)} required disabled={disabled} /><button type="button" aria-label={`Increase ${label}`} onClick={() => adjust(1)} disabled={disabled || value >= bounds.max}>+</button></span><small>{bounds.min}-{bounds.max} px</small></label>;
}

function HeroImageControl({ kind, label, initialPath, initialVisible, initialOpacity, guidance, disabled }: { kind: "Background" | "Profile"; label: string; initialPath: string; initialVisible: boolean; initialOpacity: number; guidance: string; disabled: boolean }) {
  const [path, setPath] = useState(initialPath);
  const [uploading, setUploading] = useState(false);
  const [message, setMessage] = useState("");
  const prefix = `hero${kind}`;
  const choose = async (file: File | undefined) => {
    if (!file) return;
    setUploading(true); setMessage("");
    try { setPath(await uploadImage(file)); setMessage(`${label} uploaded. Save the Draft to retain this selection.`); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Image upload failed."); }
    finally { setUploading(false); }
  };
  return <fieldset className="hero-media-control"><legend>{label}</legend><input type="hidden" name={`${prefix}ImagePath`} value={path} />
    <label className="visibility-control"><input name={`${prefix === "heroBackground" ? "heroShowBackgroundImage" : "heroShowProfileImage"}`} type="checkbox" defaultChecked={initialVisible} disabled={disabled} /> Show on Website</label>
    <NumberStepper name={`${prefix}ImageOpacity`} label={kind === "Background" ? "Background Image Visibility" : "Opacity"} initial={initialOpacity} bounds={{ min: 0, max: kind === "Background" ? 200 : 100 }} disabled={disabled} />
    {kind === "Background" ? <p className="field-note">100 keeps the standard Hero appearance. Increase above 100 to make the background image clearer.</p> : null}
    <p className="field-note hero-image-guidance">Accepted formats: JPEG, PNG, GIF, WebP<br />Maximum file size: 5 MB<br />Recommended dimensions: {guidance}</p>
    {path ? <Image className={kind === "Profile" ? "home-profile-preview" : "home-background-preview"} src={path} alt={`${label} preview`} width={kind === "Profile" ? 400 : 800} height={kind === "Profile" ? 400 : 450} unoptimized /> : <p className="field-note">No image selected. Nothing broken will be rendered publicly.</p>}
    <label className="upload-control">{path ? "Replace image" : "Upload image"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => void choose(event.target.files?.[0])} disabled={disabled || uploading} /></label>
    {path ? <button className="remove-image-button" type="button" onClick={() => { setPath(""); setMessage(`${label} removed from this Draft.`); }} disabled={disabled || uploading}>Remove</button> : null}
    {message ? <p className="field-note" role="status">{message}</p> : null}
  </fieldset>;
}

export function HomePageForm({ config, postOptions, version, canEdit, canPublish, result }: { config: HomeConfig; postOptions: PostOption[]; version: number; canEdit: boolean; canPublish: boolean; result?: string }) {
  const [state, action, pending] = useActionState(saveHomePage, {} as HomeFormState);
  const [order, setOrder] = useState<HomeConfig["sectionOrder"]>(config.sectionOrder);
  const disabled = !canEdit || pending;
  const move = (index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= order.length) return; const next = [...order]; [next[index], next[target]] = [next[target], next[index]]; setOrder(next); };
  return <section className="home-cms-page"><div className="page-heading"><p className="page-eyebrow">Pages</p><h1>Home Page</h1><p>Edit a complete Draft, then publish it atomically when ready. Header and Footer remain separately managed.</p></div>{result === "draft" ? <p className="success-message">Home Page Draft saved.</p> : null}{result === "publish" ? <p className="success-message">Home Page changes published.</p> : null}{result === "stale" ? <p className="form-error">This Draft changed after you opened it. Reload before saving.</p> : null}<form className="home-cms-form" action={action}><input type="hidden" name="expectedVersion" value={version} /><input type="hidden" name="sectionOrder" value={JSON.stringify(order)} />{state.error ? <p className="form-error">{state.error}</p> : null}
    <section className="form-section"><div className="section-heading"><h2>General / SEO</h2><p>Optional metadata for the public homepage.</p></div><label>SEO Title<input name="seoTitle" defaultValue={config.seoTitle} maxLength={200} disabled={disabled} /><small>Approximately 50-60 characters is commonly recommended.</small></label><label>SEO Description<textarea name="seoDescription" defaultValue={config.seoDescription} maxLength={500} rows={4} disabled={disabled} /><small>Approximately 150-160 characters is commonly recommended.</small></label></section>
    <section className="form-section hero-admin-section"><div className="section-heading"><h2>Hero</h2><p>Hero media and typography are saved in the same Draft snapshot as its content.</p></div><div><h3>Hero Visibility</h3><label className="visibility-control"><input name="heroVisible" type="checkbox" defaultChecked={config.hero.visible} disabled={disabled} /> Visible on public homepage</label></div>
      <HeroImageControl kind="Background" label="Background Image" initialPath={config.hero.backgroundImagePath} initialVisible={config.hero.showBackgroundImage} initialOpacity={config.hero.backgroundImageOpacity} guidance="landscape, at least 1600 × 900 px" disabled={disabled} />
      <HeroImageControl kind="Profile" label="Profile Image" initialPath={config.hero.profileImagePath} initialVisible={config.hero.showProfileImage} initialOpacity={config.hero.profileImageOpacity} guidance="square, at least 500 × 500 px" disabled={disabled} />
      <div className="hero-field-group"><h3>Eyebrow</h3><label className="visibility-control"><input name="heroShowEyebrow" type="checkbox" defaultChecked={config.hero.showEyebrow} disabled={disabled} /> Visible on public homepage</label><label>Text<input name="heroEyebrow" defaultValue={config.hero.eyebrow} maxLength={100} required disabled={disabled} /></label><NumberStepper name="heroEyebrowSize" label="Size" initial={config.hero.eyebrowSize} bounds={heroSizeBounds.eyebrow} disabled={disabled} /></div>
      <div className="hero-field-group"><h3>Heading</h3><label className="visibility-control"><input name="heroShowHeading" type="checkbox" defaultChecked={config.hero.showHeading} disabled={disabled} /> Visible on public homepage</label><label>Text<input name="heroHeading" defaultValue={config.hero.heading} maxLength={200} required disabled={disabled} /></label><NumberStepper name="heroHeadingSize" label="Size" initial={config.hero.headingSize} bounds={heroSizeBounds.heading} disabled={disabled} /></div>
      <div className="hero-field-group"><h3>Description</h3><label className="visibility-control"><input name="heroShowDescription" type="checkbox" defaultChecked={config.hero.showDescription} disabled={disabled} /> Visible on public homepage</label><label>Text<textarea name="heroDescription" defaultValue={config.hero.description} maxLength={1000} rows={4} required disabled={disabled} /></label><NumberStepper name="heroDescriptionSize" label="Size" initial={config.hero.descriptionSize} bounds={heroSizeBounds.description} disabled={disabled} /></div>
      <div className="hero-field-group"><h3>CTA</h3><label className="visibility-control"><input name="heroShowCta" type="checkbox" defaultChecked={config.hero.showCta} disabled={disabled} /> Visible on public homepage</label><label>Label<input name="heroCtaLabel" defaultValue={config.hero.ctaLabel} maxLength={100} disabled={disabled} /></label><label>Destination<select name="heroCtaDestination" defaultValue={config.hero.ctaDestination} required disabled={disabled}>{heroDestinations.map((destination) => <option key={destination.path} value={destination.path}>{destination.label} — {destination.path}</option>)}</select></label></div>
    </section>
    <section className="form-section"><div className="section-heading"><h2>Featured Story</h2><p>Resolve the latest eligible story or retain one exact published post UUID.</p></div><label className="visibility-control"><input name="featuredVisible" type="checkbox" defaultChecked={config.featuredStory.visible} disabled={disabled} /> Visible on public homepage</label><label>Source<select name="featuredSourceMode" defaultValue={config.featuredStory.sourceMode} disabled={disabled}><option value="latest">Latest Published Post</option><option value="manual">Select Post Manually</option></select></label><label>Manual Featured Story<PostSelect name="featuredPostId" value={config.featuredStory.selectedPostId} posts={postOptions} disabled={disabled} /><small>Required only in Manual mode. Parent-, Child-, and unassigned published posts are included.</small></label></section>
    <section className="form-section"><div className="section-heading"><h2>Latest &amp; Trending Stories</h2><p>Automatic uses five latest plus four genuinely most-viewed stories; Manual preserves up to nine exact UUIDs.</p></div><label className="visibility-control"><input name="latestVisible" type="checkbox" defaultChecked={config.latestStories.visible} disabled={disabled} /> Visible on public homepage</label><label>Heading<input name="latestHeading" defaultValue={config.latestStories.heading} required disabled={disabled} /></label><label>Description<textarea name="latestDescription" defaultValue={config.latestStories.description} rows={3} required disabled={disabled} /></label><label>Selection Mode<select name="latestSelectionMode" defaultValue={config.latestStories.selectionMode} disabled={disabled}><option value="automatic">Automatic</option><option value="manual">Manual Selection</option></select></label><div className="manual-story-slots">{Array.from({ length: 9 }, (_, index) => <label key={index}>Story {index + 1}<PostSelect name={`manualPostId${index + 1}`} value={config.latestStories.manualPostIds[index]} posts={postOptions} disabled={disabled} /></label>)}</div><NumberStepper name="latestRotationSeconds" label="Rotation interval (seconds)" initial={config.latestStories.rotationSeconds} bounds={{ min: 10, max: 60 }} disabled={disabled} /></section>
    <section className="form-section"><div className="section-heading"><h2>Section Order</h2><p>Hero, Featured Story, and Latest &amp; Trending can be ordered.</p></div><ol className="section-order">{order.map((section, index) => <li key={section}><span>{labels[section]}</span><div><button type="button" onClick={() => move(index, -1)} disabled={disabled || index === 0}>Move Up</button><button type="button" onClick={() => move(index, 1)} disabled={disabled || index === sectionIds.length - 1}>Move Down</button></div></li>)}</ol></section>
    <div className="home-cms-actions">{canEdit ? <button type="submit" name="intent" value="draft" disabled={pending}>{pending ? "Saving…" : "Save Draft"}</button> : null}{canPublish ? <button className="primary-action" type="submit" name="intent" value="publish" disabled={pending}>{pending ? "Publishing…" : "Publish Changes"}</button> : null}</div></form></section>;
}
