"use client";
import { useActionState, useState } from "react";
import { saveHomePage, type HomeFormState } from "@/app/(admin)/pages/home/actions";
import { type HomeConfig, sectionIds } from "@/src/home-page/config";
const labels = { hero: "Hero", latestStories: "Latest Stories", categoryDiscovery: "Category Discovery" };
export function HomePageForm({ config, version, canEdit, canPublish, result }: { config: HomeConfig; version: number; canEdit: boolean; canPublish: boolean; result?: string }) {
  const [state, action, pending] = useActionState(saveHomePage, {} as HomeFormState);
  const [order, setOrder] = useState<HomeConfig["sectionOrder"]>(config.sectionOrder);
  const move = (index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= order.length) return; const next = [...order]; [next[index], next[target]] = [next[target], next[index]]; setOrder(next); };
  return <section className="home-cms-page"><div className="page-heading"><p className="page-eyebrow">Pages</p><h1>Home Page</h1><p>Edit a complete Draft, then publish it atomically when ready. Header and Footer remain separately managed.</p></div>{result === "draft" ? <p className="success-message">Home Page Draft saved.</p> : null}{result === "publish" ? <p className="success-message">Home Page changes published.</p> : null}{result === "stale" ? <p className="form-error">This Draft changed after you opened it. Reload before saving.</p> : null}<form className="home-cms-form" action={action}><input type="hidden" name="expectedVersion" value={version} /><input type="hidden" name="sectionOrder" value={JSON.stringify(order)} />{state.error ? <p className="form-error">{state.error}</p> : null}
    <section className="form-section"><div className="section-heading"><h2>General / SEO</h2><p>Optional metadata for the public homepage.</p></div><label>SEO Title<input name="seoTitle" defaultValue={config.seoTitle} maxLength={200} disabled={!canEdit || pending} /><small>Approximately 50â€“60 characters is commonly recommended.</small></label><label>SEO Description<textarea name="seoDescription" defaultValue={config.seoDescription} maxLength={500} rows={4} disabled={!canEdit || pending} /><small>Approximately 150â€“160 characters is commonly recommended.</small></label></section>
    <section className="form-section"><div className="section-heading"><h2>Hero</h2></div><label className="visibility-control"><input name="heroVisible" type="checkbox" defaultChecked={config.hero.visible} disabled={!canEdit || pending} /> Visible on public homepage</label><label>Eyebrow<input name="heroEyebrow" defaultValue={config.hero.eyebrow} required disabled={!canEdit || pending} /></label><label>Heading<input name="heroHeading" defaultValue={config.hero.heading} required disabled={!canEdit || pending} /></label><label>Description<textarea name="heroDescription" defaultValue={config.hero.description} rows={4} required disabled={!canEdit || pending} /></label><label>CTA Label<input name="heroCtaLabel" defaultValue={config.hero.ctaLabel} required disabled={!canEdit || pending} /></label><label>CTA Destination<input name="heroCtaDestination" defaultValue={config.hero.ctaDestination} required disabled={!canEdit || pending} /><small>Safe internal path or http(s) URL.</small></label></section>
    <section className="form-section"><div className="section-heading"><h2>Latest Stories</h2><p>Posts remain dynamic and published-only.</p></div><label className="visibility-control"><input name="latestVisible" type="checkbox" defaultChecked={config.latestStories.visible} disabled={!canEdit || pending} /> Visible on public homepage</label><label>Heading<input name="latestHeading" defaultValue={config.latestStories.heading} required disabled={!canEdit || pending} /></label><label>Description<textarea name="latestDescription" defaultValue={config.latestStories.description} rows={3} required disabled={!canEdit || pending} /></label><label>Number of Posts<input name="latestPostCount" type="number" min={1} max={12} defaultValue={config.latestStories.postCount} required disabled={!canEdit || pending} /></label></section>
    <section className="form-section"><div className="section-heading"><h2>Category Discovery</h2><p>Categories remain dynamic and hierarchical.</p></div><label className="visibility-control"><input name="categoryVisible" type="checkbox" defaultChecked={config.categoryDiscovery.visible} disabled={!canEdit || pending} /> Visible on public homepage</label><label>Heading<input name="categoryHeading" defaultValue={config.categoryDiscovery.heading} required disabled={!canEdit || pending} /></label><label>Description<textarea name="categoryDescription" defaultValue={config.categoryDiscovery.description} rows={3} required disabled={!canEdit || pending} /></label></section>
    <section className="form-section"><div className="section-heading"><h2>Section Order</h2><p>Only the three known homepage sections can be ordered.</p></div><ol className="section-order">{order.map((section, index) => <li key={section}><span>{labels[section]}</span><div><button type="button" onClick={() => move(index, -1)} disabled={!canEdit || pending || index === 0}>Move Up</button><button type="button" onClick={() => move(index, 1)} disabled={!canEdit || pending || index === sectionIds.length - 1}>Move Down</button></div></li>)}</ol></section>
    <div className="home-cms-actions">{canEdit ? <button type="submit" name="intent" value="draft" disabled={pending}>{pending ? "Savingâ€¦" : "Save Draft"}</button> : null}{canPublish ? <button className="primary-action" type="submit" name="intent" value="publish" disabled={pending}>{pending ? "Publishingâ€¦" : "Publish Changes"}</button> : null}</div></form></section>;
}
