"use client";
import { useActionState, useState } from "react";
import { saveTheme } from "@/app/(admin)/theme/actions";
import { defaultThemeConfig, type ThemeConfig } from "@/src/theme/config";

const fontLabels = { editorial: "Editorial serif", modern: "Modern sans-serif", system: "System default" } as const;
const colorGroups = { "Global colors": "global", "Header & announcement": "header", "Footer": "footer", "Cards & surfaces": "card", "Buttons": "button" } as const;
const labels: Record<string, string> = { pageBackground:"Page background",surfaceBackground:"Surface background",primaryText:"Primary text",mutedText:"Muted text",accent:"Accent",link:"Link",linkHover:"Link hover",border:"Border",background:"Background",text:"Text",hover:"Hover / active",dropdownBackground:"Dropdown background",dropdownText:"Dropdown text",dropdownHover:"Dropdown hover",announcementBackground:"Announcement background",announcementText:"Announcement text",directoryBackground:"Category Directory background",parentHeading:"Parent heading",childLink:"Child link",mainBackground:"Main Footer background",heading:"Heading",bodyText:"Body text",divider:"Divider",attributionBackground:"Attribution background",attributionText:"Attribution text",hoverBorder:"Hover border",primaryBackground:"Primary background",primaryHover:"Primary hover",secondaryBackground:"Secondary background",secondaryText:"Secondary text",secondaryBorder:"Secondary border" };

function Stepper({ label, value, min, max, suffix, onChange, disabled }: { label:string;value:number;min:number;max:number;suffix:string;onChange:(value:number)=>void;disabled:boolean }) { return <label>{label}<span className="number-stepper"><button type="button" onClick={()=>onChange(Math.max(min,value-1))} disabled={disabled}>−</button><input type="number" min={min} max={max} value={value} onChange={(event)=>onChange(Number(event.target.value))} disabled={disabled}/><button type="button" onClick={()=>onChange(Math.min(max,value+1))} disabled={disabled}>+</button></span><small>{min}–{max}{suffix}</small></label>; }
function contrastRatio(a:string,b:string){const luminance=(hex:string)=>{const channels=[1,3,5].map(index=>parseInt(hex.slice(index,index+2),16)/255).map(value=>value<=.03928?value/12.92:((value+.055)/1.055)**2.4);return .2126*channels[0]+.7152*channels[1]+.0722*channels[2]};const [light,dark]=[luminance(a),luminance(b)].sort((x,y)=>y-x);return (light+.05)/(dark+.05)}

export function ThemeForm({ config, version, canEdit, canPublish, result }: { config:ThemeConfig;version:number;canEdit:boolean;canPublish:boolean;result?:string }) {
  const [state, action, pending] = useActionState(saveTheme, {});
  const [theme, setTheme] = useState(config);
  const disabled = !canEdit || pending;
  const setTypography = <K extends keyof ThemeConfig["typography"]>(key:K,value:ThemeConfig["typography"][K])=>setTheme(current=>({...current,typography:{...current.typography,[key]:value}}));
  const setLayout = <K extends keyof ThemeConfig["layout"]>(key:K,value:ThemeConfig["layout"][K])=>setTheme(current=>({...current,layout:{...current.layout,[key]:value}}));
  const setColor=(group:keyof Pick<ThemeConfig,"global"|"header"|"footer"|"card"|"button">,key:string,value:string)=>setTheme(current=>({...current,[group]:{...current[group],[key]:value.toLowerCase()}}));
  const previewStyle = { background:theme.global.pageBackground,color:theme.global.primaryText,fontSize:theme.typography.bodySize,borderColor:theme.global.border,borderRadius:theme.layout.radius };
  const contrastWarnings=[["Page text",theme.global.primaryText,theme.global.pageBackground],["Header links",theme.header.link,theme.header.background],["Footer text",theme.footer.bodyText,theme.footer.mainBackground],["Primary button",theme.button.primaryText,theme.button.primaryBackground]].filter(([,foreground,background])=>contrastRatio(foreground,background)<4.5).map(([label])=>label);
  return <section className="home-cms-page theme-cms-page"><div className="page-heading"><p className="page-eyebrow">Universal public defaults</p><h1>Theme</h1><p>Control validated global visual tokens. Specialized Home Hero and article formatting remain authoritative.</p></div>{result?<p className="success-message">Theme {result==="publish"?"published":result==="reset"?"Draft reset":"Draft saved"}.</p>:null}<form className="home-cms-form" action={action}><input type="hidden" name="expectedVersion" value={version}/><input type="hidden" name="theme" value={JSON.stringify(theme)}/>{state.error?<p className="form-error">{state.error}</p>:null}
    <section className="form-section"><h2>Typography</h2>{(["bodyFont","headingFont","navigationFont"] as const).map(key=><label key={key}>{key==="bodyFont"?"Body font":key==="headingFont"?"Heading font":"Navigation/Menu font"}<select value={theme.typography[key]} onChange={event=>setTypography(key,event.target.value as ThemeConfig["typography"][typeof key])} disabled={disabled}>{Object.entries(fontLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}<Stepper label="Base body size" value={theme.typography.bodySize} min={14} max={24} suffix=" px" onChange={value=>setTypography("bodySize",value)} disabled={disabled}/><Stepper label="General heading scale" value={theme.typography.headingScale} min={80} max={140} suffix="%" onChange={value=>setTypography("headingScale",value)} disabled={disabled}/></section>
    {Object.entries(colorGroups).map(([title,group])=><section className="form-section" key={group}><h2>{title}</h2><div className="theme-color-grid">{Object.entries(theme[group as keyof typeof colorGroups extends never ? never : keyof Pick<ThemeConfig,"global"|"header"|"footer"|"card"|"button">]).map(([key,value])=><label key={key}>{labels[key]??key}<span className="theme-color-input"><input type="color" value={value as string} onChange={event=>setColor(group as keyof Pick<ThemeConfig,"global"|"header"|"footer"|"card"|"button">,key,event.target.value)} disabled={disabled}/><input value={value as string} pattern="#[0-9a-f]{6}" onChange={event=>setColor(group as keyof Pick<ThemeConfig,"global"|"header"|"footer"|"card"|"button">,key,event.target.value)} disabled={disabled}/></span></label>)}</div></section>)}
    <section className="form-section"><h2>Layout</h2><label>General content width<select value={theme.layout.contentWidth} onChange={event=>setLayout("contentWidth",event.target.value as ThemeConfig["layout"]["contentWidth"])} disabled={disabled}><option value="narrow">Narrow</option><option value="standard">Standard</option><option value="wide">Wide</option></select></label><label>Shadow strength<select value={theme.layout.shadow} onChange={event=>setLayout("shadow",event.target.value as ThemeConfig["layout"]["shadow"])} disabled={disabled}><option value="none">None</option><option value="subtle">Subtle</option><option value="medium">Medium</option></select></label><Stepper label="Border radius" value={theme.layout.radius} min={0} max={24} suffix=" px" onChange={value=>setLayout("radius",value)} disabled={disabled}/><Stepper label="Section spacing" value={theme.layout.sectionSpacing} min={24} max={120} suffix=" px" onChange={value=>setLayout("sectionSpacing",value)} disabled={disabled}/></section>
    <section className="form-section"><h2>Theme Preview</h2>{contrastWarnings.length?<p className="contrast-warning" role="status">Possible low contrast: {contrastWarnings.join(", ")}. Review before publishing.</p>:<p className="field-note">No obvious text contrast warning detected.</p>}<div className="theme-preview" style={previewStyle}><nav style={{background:theme.header.background,color:theme.header.link}}>Menu <span>Dropdown</span></nav><h3 style={{fontSize:`${theme.typography.headingScale}%`}}>Editorial heading</h3><p style={{color:theme.global.mutedText}}>A paragraph showing the current Draft Theme. <a style={{color:theme.global.link}}>Preview link</a></p><button type="button" style={{background:theme.button.primaryBackground,color:theme.button.primaryText}}>Primary button</button><article style={{background:theme.card.background,color:theme.card.text,borderColor:theme.card.border}}><strong>Story card</strong><small style={{color:theme.card.mutedText}}>Card supporting text</small></article><footer style={{background:theme.footer.mainBackground,color:theme.footer.bodyText}}>Footer sample</footer></div><p className="field-note">This lightweight indicator does not claim WCAG certification.</p></section>
    <div className="home-cms-actions">{canEdit?<button type="submit" name="intent" value="reset" onClick={event=>{if(!confirm("Reset this Draft to Eraasim defaults? Published Theme will not change."))event.preventDefault();else setTheme(defaultThemeConfig)}} disabled={pending}>Reset Draft to Eraasim Defaults</button>:null}{canEdit?<button name="intent" value="draft" disabled={pending}>Save Draft</button>:null}{canPublish?<button className="primary-action" name="intent" value="publish" disabled={pending}>Publish Changes</button>:null}</div>
  </form></section>;
}
