"use server";
import { and, eq, isNotNull, isNull, ne } from "drizzle-orm";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requirePermission } from "@/src/auth/authorization";
import { contentHasBody, parseAndNormalizeContent } from "@/src/blog/content";
import { resolveFeaturedImagePath } from "@/src/blog/featured-image";
import { db } from "@/src/db";
import { activityLogs, genericPages } from "@/src/db/schema";
import { genericPagePublishing, genericPageSlugError, normalizeGenericPageSlug, parseGenericPageForm } from "@/src/generic-pages/generic-page";

export type GenericPageState={error?:string;fieldErrors?:Record<string,string[]>};
const identity=z.object({pageId:z.uuid(),expectedUpdatedAt:z.iso.datetime()});
const lifecycle=z.object({pageId:z.uuid(),action:z.enum(["delete","restore","permanent-delete","unpublish"])});
const optional=(value?:string)=>value||null;

function normalized(formData: FormData) {
  const parsed = parseGenericPageForm(formData);
  if (!parsed.success) return { error: { error: "Review the highlighted fields.", fieldErrors: parsed.error.flatten().fieldErrors } };
  const slug = normalizeGenericPageSlug(parsed.data.slug);
  const slugError = genericPageSlugError(slug);
  if (slugError) return { error: { fieldErrors: { slug: [slugError] } } };
  let content: Record<string, unknown>;
  try { content = parseAndNormalizeContent(parsed.data.content); }
  catch (error) { return { error: { fieldErrors: { content: [error instanceof Error ? error.message : "Content is invalid."] } } }; }
  if (!contentHasBody(content)) return { error: { fieldErrors: { content: ["Add page content before saving."] } } };
  const featuredImagePath = resolveFeaturedImagePath(parsed.data.featuredImagePath, parsed.data.featuredImageIntent);
  if (featuredImagePath && !/^\/api\/uploads\/[0-9a-f-]{36}\.(?:jpe?g|png|webp|gif)$/i.test(featuredImagePath)) return { error: { fieldErrors: { featuredImagePath: ["Upload the featured image through Eraasim."] } } };
  return { data: parsed.data, slug, content, featuredImagePath };
}

export async function createGenericPage(_state:GenericPageState,formData:FormData):Promise<GenericPageState>{const input=normalized(formData);if("error" in input) return input.error as GenericPageState;const{data,slug,content,featuredImagePath}=input;if(data.intent==="preserve"||data.intent==="unpublished")return{error:"Choose Save Draft or Publish."};const{session}=await requirePermission(data.intent==="published"?"pages.generic.publish":"pages.generic.create");const now=new Date(),publishing=genericPagePublishing({status:"draft",publishedAt:null},data.intent,now);try{await db.transaction(async tx=>{const[page]=await tx.insert(genericPages).values({title:data.title,slug,content,featuredImagePath,featuredImageAlt:optional(data.featuredImageAlt),seoTitle:optional(data.seoTitle),seoDescription:optional(data.seoDescription),...publishing,createdById:session.user.id,updatedById:session.user.id}).returning({id:genericPages.id});await tx.insert(activityLogs).values([{staffAccountId:session.user.id,action:"page.created",entityType:"generic_page",entityId:page.id,description:"Generic Page created.",metadata:{slug,status:publishing.status}},...(publishing.status==="published"?[{staffAccountId:session.user.id,action:"page.published",entityType:"generic_page",entityId:page.id,description:"Generic Page published.",metadata:{slug,status:publishing.status}}]:[])]);})}catch(error){if(typeof error==="object"&&error&&"code"in error&&String(error.code)==="23505")return{fieldErrors:{slug:["This slug is already in use."]}};return{error:"The Page could not be created."}}redirect("/pages?created=1")}

export async function updateGenericPage(_state:GenericPageState,formData:FormData):Promise<GenericPageState>{const id=identity.safeParse(Object.fromEntries(formData));if(!id.success)return{error:"This edit request is invalid."};const input=normalized(formData);if("error" in input) return input.error as GenericPageState;const{data,slug,content,featuredImagePath}=input;const{session}=await requirePermission(data.intent==="published"||data.intent==="unpublished"?"pages.generic.publish":"pages.generic.edit");try{await db.transaction(async tx=>{const[current]=await tx.select().from(genericPages).where(and(eq(genericPages.id,id.data.pageId),isNull(genericPages.deletedAt))).limit(1).for("update");if(!current)throw new Error("MISSING");if(current.updatedAt.toISOString()!==id.data.expectedUpdatedAt)throw new Error("STALE");const[duplicate]=await tx.select({id:genericPages.id}).from(genericPages).where(and(eq(genericPages.slug,slug),ne(genericPages.id,current.id))).limit(1);if(duplicate)throw new Error("DUPLICATE");const publishing=genericPagePublishing(current,data.intent),now=new Date();await tx.update(genericPages).set({title:data.title,slug,content,featuredImagePath,featuredImageAlt:optional(data.featuredImageAlt),seoTitle:optional(data.seoTitle),seoDescription:optional(data.seoDescription),...publishing,updatedById:session.user.id,updatedAt:now}).where(eq(genericPages.id,current.id));const events=["page.updated",...(publishing.status!==current.status?[publishing.status==="published"?"page.published":"page.unpublished"]:[])];await tx.insert(activityLogs).values(events.map(action=>({staffAccountId:session.user.id,action,entityType:"generic_page",entityId:current.id,description:`Generic Page ${action.split(".")[1]}.`,metadata:{slug,status:publishing.status}})))})}catch(error){const message=error instanceof Error?error.message:"";if(message==="DUPLICATE")return{fieldErrors:{slug:["This slug is already in use."]}};if(message==="STALE")return{error:"This Page changed after you opened it. Reload before saving."};if(message==="MISSING")return{error:"This Page is no longer editable."};return{error:"The Page could not be updated."}}redirect(`/pages/${id.data.pageId}/edit?updated=1`)}

export async function changeGenericPageLifecycle(formData:FormData){const parsed=lifecycle.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("Invalid Page lifecycle request.");const{session}=await requirePermission(parsed.data.action==="unpublish"?"pages.generic.publish":"pages.generic.delete");await db.transaction(async tx=>{const deleted=parsed.data.action==="restore"||parsed.data.action==="permanent-delete";const[page]=await tx.select({id:genericPages.id,slug:genericPages.slug,status:genericPages.status}).from(genericPages).where(and(eq(genericPages.id,parsed.data.pageId),deleted?isNotNull(genericPages.deletedAt):isNull(genericPages.deletedAt))).limit(1).for("update");if(!page)throw new Error("Page not found.");if(parsed.data.action==="permanent-delete")await tx.delete(genericPages).where(eq(genericPages.id,page.id));else{const values=parsed.data.action==="delete"?{deletedAt:new Date()} : parsed.data.action==="restore"?{deletedAt:null,status:"unpublished" as const,updatedAt:new Date(),updatedById:session.user.id}:{status:"unpublished" as const,updatedAt:new Date(),updatedById:session.user.id};await tx.update(genericPages).set(values).where(eq(genericPages.id,page.id))}const event={delete:"page.deleted",restore:"page.restored","permanent-delete":"page.permanently_deleted",unpublish:"page.unpublished"}[parsed.data.action];await tx.insert(activityLogs).values({staffAccountId:session.user.id,action:event,entityType:"generic_page",entityId:page.id,description:`Generic Page ${parsed.data.action}.`,metadata:{slug:page.slug,status:parsed.data.action==="restore"?"unpublished":page.status}})});redirect(parsed.data.action==="restore"||parsed.data.action==="permanent-delete"?"/pages/deleted":"/pages")}
