import { z } from "zod";
export const socialPlatforms=["facebook","instagram","youtube","x","linkedin"] as const;
const social=z.object({platform:z.enum(socialPlatforms),url:z.string().trim().max(2048).refine(value=>{if(!value)return true;try{return new URL(value).protocol==="https:"}catch{return false}},"Use a valid HTTPS URL."),visible:z.boolean()});
const pageLink=z.object({pageId:z.string().uuid(),visible:z.boolean(),order:z.number().int().min(0).max(99)});
export const footerConfigSchema=z.object({categoryDirectory:z.object({visible:z.boolean(),heading:z.string().trim().min(1).max(120)}),content:z.object({heading:z.string().trim().max(120),description:z.string().trim().max(500)}),pageLinks:z.array(pageLink).max(30).refine(items=>new Set(items.map(item=>item.pageId)).size===items.length,"Pages may be selected only once."),socialLinks:z.array(social).length(socialPlatforms.length).refine(items=>new Set(items.map(item=>item.platform)).size===socialPlatforms.length,"Each social platform must appear once.")});
export type FooterConfig=z.infer<typeof footerConfigSchema>;
export const defaultFooterConfig:FooterConfig={categoryDirectory:{visible:true,heading:"Explore Categories"},content:{heading:"Eraasim",description:"Stories of culture, food and places—gathered with curiosity and care."},pageLinks:[],socialLinks:socialPlatforms.map(platform=>({platform,url:"",visible:false}))};
export function parseFooterConfig(value:unknown){return footerConfigSchema.safeParse(value)}
export function parseFooterForm(formData:FormData){let pageLinks:unknown=[];try{pageLinks=JSON.parse(String(formData.get("pageLinks")??"[]"))}catch{/* schema reports */}return footerConfigSchema.safeParse({categoryDirectory:{visible:formData.get("directoryVisible")==="on",heading:String(formData.get("directoryHeading")??"")},content:{heading:String(formData.get("contentHeading")??""),description:String(formData.get("contentDescription")??"")},pageLinks,socialLinks:socialPlatforms.map(platform=>({platform,url:String(formData.get(`social-${platform}`)??""),visible:formData.get(`social-${platform}-visible`)==="on"}))})}
