import Link from "next/link";
import { PostGrid } from "@/components/post-grid";
import { getLatestPosts, getPublicCategories } from "@/src/public-blog";

export const dynamic = "force-dynamic";
export default async function Home() {
  const [posts, categories] = await Promise.all([getLatestPosts(6), getPublicCategories()]);
  const parents = categories.filter((category) => category.parentId === null);
  const children = categories.filter((category) => category.parentId !== null);
  return <><section className="hero"><div className="hero-copy"><p className="eyebrow">Culture Â· Food Â· Places</p><h1>Stories rooted in people and place.</h1><p>Eraasim is a journal for thoughtful encounters, lived experiences and the details that make a place memorable.</p><Link className="primary-link" href="/blog">Explore the journal <span aria-hidden="true">â†’</span></Link></div><div className="hero-mark" aria-hidden="true"><span>E</span></div></section><section className="content-section latest-section" aria-labelledby="latest-heading"><div className="section-title"><div><p className="eyebrow">From the journal</p><h2 id="latest-heading">Latest stories</h2><p>Freshly published journeys, observations and reflections.</p></div><Link className="text-link" href="/blog">View all stories <span aria-hidden="true">â†’</span></Link></div><PostGrid items={posts} /></section>{parents.length ? <section id="categories" className="category-discovery" aria-labelledby="categories-heading"><div className="category-discovery-inner"><div className="section-title"><div><p className="eyebrow">Find your way</p><h2 id="categories-heading">Explore by category</h2><p>Follow a broad theme or step into one of its more specific paths.</p></div></div><div className="category-family-grid">{parents.map((parent) => <article className="category-family" key={parent.id}><Link href={`/categories/${parent.slug}`}><span>Parent category</span><h3>{parent.name}</h3>{parent.description ? <p>{parent.description}</p> : null}</Link>{children.some((child) => child.parentId === parent.id) ? <nav aria-label={`${parent.name} child categories`}>{children.filter((child) => child.parentId === parent.id).map((child) => <Link key={child.id} href={`/categories/${child.slug}`}>{child.name}<span aria-hidden="true">â†—</span></Link>)}</nav> : null}</article>)}</div></div></section> : null}</>;
}
