import type { CSSProperties } from "react";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { StoryCarousel } from "@/components/story-carousel";
import { firstYouTubeId, structuredExcerpt } from "@/src/featured-story";
import { getPublishedHomeConfig, type HomeConfig } from "@/src/home-page";
import { resolveHeroBackgroundVisibility } from "@/src/hero-background";
import { availablePublicMediaUrl, publicMediaUrl } from "@/src/media";
import { getFeaturedStory, getHomeStoryPool } from "@/src/public-blog";
export const dynamic = "force-dynamic";
export async function generateMetadata(): Promise<Metadata> { const config = await getPublishedHomeConfig(); return { title: config.seoTitle || "Eraasim", description: config.seoDescription || "Stories of culture, food and places." }; }
export default async function Home() {
  const config = await getPublishedHomeConfig();
  const [backgroundImage, profileImage, featured, stories] = await Promise.all([config.hero.showBackgroundImage ? availablePublicMediaUrl(config.hero.backgroundImagePath) : null, config.hero.showProfileImage ? availablePublicMediaUrl(config.hero.profileImagePath) : null, config.featuredStory.visible ? getFeaturedStory(config.featuredStory.sourceMode, config.featuredStory.selectedPostId) : null, config.latestStories.visible ? getHomeStoryPool(config.latestStories.selectionMode, config.latestStories.manualPostIds) : []]);
  const backgroundVisibility = resolveHeroBackgroundVisibility(config.hero.backgroundImageOpacity);
  const heroStyle = { "--hero-eyebrow-size": `${config.hero.eyebrowSize}px`, "--hero-heading-size": `${config.hero.headingSize}px`, "--hero-description-size": `${config.hero.descriptionSize}px`, "--hero-background-opacity": backgroundVisibility.imageOpacity, "--hero-overlay-opacity": backgroundVisibility.overlayOpacity, "--hero-profile-opacity": config.hero.profileImageOpacity / 100, ...(backgroundImage ? { "--hero-background-image": `url(\"${backgroundImage}\")` } : {}) } as CSSProperties;
  const youtube = featured ? firstYouTubeId(featured.content) : null; const featuredImage = featured ? publicMediaUrl(featured.featuredImagePath) : null;
  const sections: Record<HomeConfig["sectionOrder"][number], React.ReactNode> = {
    hero: config.hero.visible ? <section className={`hero${backgroundImage ? " hero-with-background" : ""}`} style={heroStyle} key="hero"><div className="hero-copy">{config.hero.showEyebrow ? <p className="eyebrow">{config.hero.eyebrow}</p> : null}{config.hero.showHeading ? <h1>{config.hero.heading}</h1> : null}{config.hero.showDescription ? <p>{config.hero.description}</p> : null}{config.hero.showCta && config.hero.ctaLabel ? <Link className="primary-link" href={config.hero.ctaDestination}>{config.hero.ctaLabel} <span aria-hidden="true">→</span></Link> : null}</div>{profileImage ? <div className="hero-mark"><Image src={profileImage} alt="" width={800} height={800} sizes="(max-width: 640px) 0px, (max-width: 900px) 30vw, 40vw" unoptimized /></div> : config.useLegacyHeroMark ? <div className="hero-mark" aria-hidden="true"><span>E</span></div> : null}</section> : null,
    featuredStory: config.featuredStory.visible ? <section className="featured-story" key="featuredStory">{featured ? <div className="featured-story-inner"><div className="featured-copy">{featured.categoryName && featured.categorySlug ? <Link className="category-chip" href={`/categories/${featured.categorySlug}`}>{featured.categoryName}</Link> : <span className="category-chip category-unassigned">Journal</span>}<h2>{featured.title}</h2><p className="featured-summary">{featured.shortDescription}</p><p className="featured-excerpt">{structuredExcerpt(featured.content)}</p><Link className="text-link" href={`/blog/${featured.slug}`}>Continue Reading <span aria-hidden="true">→</span></Link></div><div className="featured-media">{youtube ? <iframe src={`https://www.youtube-nocookie.com/embed/${youtube}`} title={`Video for ${featured.title}`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /> : featuredImage ? <Image src={featuredImage} alt="" width={1200} height={675} unoptimized /> : <div className="image-fallback" aria-hidden="true">E</div>}</div></div> : <div className="public-empty"><p>The configured Featured Story is not currently public.</p></div>}</section> : null,
    latestStories: config.latestStories.visible ? <section className="content-section latest-section" key="latestStories"><div className="section-title"><div><p className="eyebrow">From the journal</p><h2>{config.latestStories.heading}</h2><p>{config.latestStories.description}</p></div><Link className="text-link" href="/blog">View all stories <span aria-hidden="true">→</span></Link></div><StoryCarousel stories={stories} rotationSeconds={config.latestStories.rotationSeconds} /></section> : null,
  };
  return <>{config.sectionOrder.map((id) => sections[id])}</>;
}
