import { createHash, randomBytes } from "node:crypto";
import nodemailer from "nodemailer";
const escape=(value:string)=>value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]!));
export const normalizeStaffEmail=(value:string)=>value.trim().toLowerCase();
export const newOpaqueToken=()=>randomBytes(32).toString("base64url");
export const tokenHash=(token:string)=>createHash("sha256").update(token).digest("hex");
export const tokenExpiry=(now=new Date())=>new Date(now.valueOf()+48*60*60*1000);
type Kind="invitation"|"reset";
type StaffMailEnvironment={ [key:string]:string|undefined; SMTP_HOST?:string;SMTP_PORT?:string;SMTP_SECURE?:string;SMTP_USER?:string;SMTP_APP_PASSWORD?:string;CONTACT_EMAIL_FROM?:string;ADMIN_SITE_URL?:string};
export function staffEmailTemplate(kind:Kind,token:string,email:string,origin:string){const invitation=kind==="invitation",url=`${origin}/staff/${invitation?"register":"reset-password"}/${encodeURIComponent(token)}`,heading=invitation?"You've been invited to join Eraasim":"Reset your Eraasim staff password",lead=invitation?"An administrator has invited you to create a staff account.":"An administrator requested a secure password reset for your staff account.",button=invitation?"Complete Registration":"Reset Password",expiry=invitation?"Invitation expires in 48 hours.":"This reset link expires in 2 hours.";return{url,subject:heading,text:[heading,"",lead,"",`${button}: ${url}`,"",expiry,"If you were not expecting this email, you may ignore it."].join("\n"),html:`<!doctype html><html><body style="margin:0;background:#f5f2e9;color:#1f211d;font-family:Arial,sans-serif"><table role="presentation" width="100%"><tr><td align="center" style="padding:24px"><table role="presentation" width="100%" style="max-width:600px;background:#fffef9;border:1px solid #d9d5c9"><tr><td style="padding:32px"><strong style="font-size:24px">Eraasim</strong><h1>${escape(heading)}</h1><p>${escape(lead)}</p><p><a href="${escape(url)}" style="display:inline-block;padding:12px 18px;background:#365b43;color:white;text-decoration:none">${button}</a></p><p>${expiry}</p><p style="color:#686b63;font-size:13px">If you were not expecting this email, you may ignore it.</p></td></tr></table></td></tr></table></body></html>`,email}}
export async function sendStaffEmail(kind:Kind,token:string,email:string,environment:StaffMailEnvironment=process.env,createTransport=nodemailer.createTransport){let url:URL;try{url=new URL(environment.ADMIN_SITE_URL??"")}catch{return false}const port=Number(environment.SMTP_PORT);if(!environment.SMTP_HOST||!Number.isInteger(port)||port<1||port>65535||!environment.SMTP_USER||!environment.SMTP_APP_PASSWORD||!environment.CONTACT_EMAIL_FROM||url.protocol!=="https:"||url.username||url.password)return false;const mail=staffEmailTemplate(kind,token,email,url.origin);try{await createTransport({host:environment.SMTP_HOST,port,secure:environment.SMTP_SECURE==="true",auth:{user:environment.SMTP_USER,pass:environment.SMTP_APP_PASSWORD},connectionTimeout:10_000,greetingTimeout:10_000,socketTimeout:15_000}).sendMail({from:environment.CONTACT_EMAIL_FROM,to:email,subject:mail.subject,text:mail.text,html:mail.html});return true}catch{console.error("Staff account email delivery failed.");return false}}
