"use client";
import { FormEvent, useState } from "react";
import type { PublicComment } from "@/src/comments";
type Item=Omit<PublicComment,"createdAt"|"replies">&{createdAt:Date|string;replies:(Omit<PublicComment["replies"][number],"createdAt">&{createdAt:Date|string})[]};
type SubmissionState="idle"|"submitting"|"success"|"validation-error"|"server-error";
const fmt=new Intl.DateTimeFormat("en-IN",{dateStyle:"long",timeZone:"Asia/Kolkata"});
function token(){const key="eraasim-comment-like-token",old=localStorage.getItem(key);if(old)return old;const value=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem(key,value);return value}
async function safeJson(response:Response){try{return await response.json() as{ok?:boolean;message?:string;count?:number;items?:Item[];hasMore?:boolean;nextCursor?:string|null}}catch{return{ok:false,message:"The server returned an unexpected response."}}}
export function BlogComments({postId,initial,count,hasMore,nextCursor}:{postId:string;initial:Item[];count:number;hasMore:boolean;nextCursor:string|null}){
  const[items,setItems]=useState(initial),[more,setMore]=useState(hasMore),[cursor,setCursor]=useState(nextCursor),[loading,setLoading]=useState(false),[state,setState]=useState<SubmissionState>("idle"),[message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;if(!form.reportValidity()){setState("validation-error");setMessage("Review the required comment fields.");return}setLoading(true);setState("submitting");setMessage("Submitting your comment…");try{const data=Object.fromEntries(new FormData(form)),response=await fetch("/api/comments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...data,postId})}),result=await safeJson(response);if(!response.ok||!result.ok){setState(response.status===400?"validation-error":"server-error");setMessage(result.message||"Your comment could not be submitted. Please try again.");return}setState("success");setMessage(result.message||"Your comment was submitted.");form.reset()}catch{setState("server-error");setMessage("Your comment could not be submitted. Check your connection and try again.")}finally{setLoading(false)}}
  async function load(){setLoading(true);try{const response=await fetch(`/api/comments?postId=${postId}&cursor=${encodeURIComponent(cursor??"")}`),result=await safeJson(response);if(response.ok&&result.items){setItems(old=>[...old,...result.items!.filter(item=>!old.some(existing=>existing.id===item.id))]);setMore(Boolean(result.hasMore));setCursor(result.nextCursor??null)}}finally{setLoading(false)}}
  async function like(id:string){try{const response=await fetch(`/api/comments/${id}/like`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:token()})}),result=await safeJson(response);if(response.ok&&typeof result.count==="number")setItems(old=>old.map(item=>item.id===id?{...item,likes:result.count!}:item))}catch{/* Like remains unchanged on network failure. */}}
  return <section className="blog-comments" aria-labelledby="comments-heading"><h2 id="comments-heading">Comments ({count})</h2><form className={`comment-form submission-${state}`} onSubmit={submit} noValidate><label>Name<input name="name" placeholder="Your name" required maxLength={120} aria-invalid={state==="validation-error"}/></label><label>Email<input name="email" type="email" placeholder="you@example.com" required maxLength={254} aria-invalid={state==="validation-error"}/></label><label>Comment<textarea name="comment" placeholder="Write your comment" required maxLength={5000} rows={6} aria-invalid={state==="validation-error"}/></label><label className="comment-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button disabled={loading}>{state==="submitting"?"Submitting…":"Submit Comment"}</button>{message?<p className={`comment-form-message message-${state}`} role={state==="server-error"||state==="validation-error"?"alert":"status"}>{message}</p>:null}</form><div className="comment-list">{items.map(item=><article className="comment" key={item.id}><header><strong>{item.name}</strong><time dateTime={new Date(item.createdAt).toISOString()}>{fmt.format(new Date(item.createdAt))}</time></header><p>{item.comment}</p><button type="button" onClick={()=>void like(item.id)} aria-label={`Like comment by ${item.name}`}>♡ {item.likes} Likes</button>{item.replies.map(reply=><article className="comment-reply" key={reply.id}><strong>{reply.name}</strong><span>Admin Reply</span><p>{reply.comment}</p></article>)}</article>)}</div>{more?<button className="load-comments" type="button" disabled={loading} onClick={()=>void load()}>{loading?"Loading…":"Load More Comments"}</button>:null}<span className="visually-hidden" aria-live="polite">{loading?"Loading comments":""}</span></section>}
