"use client";
import { useEffect, useState } from "react";
import type { EngagementPlatforms } from "@/src/engagement";

function token(){const key="eraasim-comment-like-token",old=localStorage.getItem(key);if(old)return old;const value=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem(key,value);return value}
export function buildShareUrls(title:string,url:string){return{whatsapp:`https://wa.me/?text=${encodeURIComponent(`${title} ${url}`)}`,facebook:`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,x:`https://twitter.com/intent/tweet?text=${encodeURIComponent(title)}&url=${encodeURIComponent(url)}`,linkedin:`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`}}
type Props={postId:string;title:string;url:string|null;likesEnabled:boolean;sharingEnabled:boolean;initialLikeCount:number;commentCount:number;commentsAvailable:boolean;platforms:EngagementPlatforms};
export function PostEngagement({postId,title,url,likesEnabled,sharingEnabled,initialLikeCount,commentCount,commentsAvailable,platforms}:Props){
  const[liked,setLiked]=useState(false),[count,setCount]=useState(initialLikeCount),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(""),[native,setNative]=useState(false);
  useEffect(()=>{void Promise.resolve(typeof navigator.share==="function").then(setNative);if(!likesEnabled)return;void fetch(`/api/posts/${postId}/like`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:token(),intent:"state"})}).then(r=>r.ok?r.json():null).then(result=>{if(result&&typeof result.liked==="boolean"&&typeof result.count==="number"){setLiked(result.liked);setCount(result.count)}}).catch(()=>{})},[likesEnabled,postId]);
  async function toggle(){setBusy(true);try{const response=await fetch(`/api/posts/${postId}/like`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:token()})}),result=await response.json() as{liked?:boolean;count?:number};if(response.ok&&typeof result.liked==="boolean"&&typeof result.count==="number"){setLiked(result.liked);setCount(result.count)}}finally{setBusy(false)}}
  async function copy(){if(!url)return;try{await navigator.clipboard.writeText(url);setFeedback("Link copied")}catch{setFeedback(`Copy this link: ${url}`)}}
  async function nativeShare(){if(!url||!navigator.share)return;try{await navigator.share({title,url})}catch{/* User cancellation is expected. */}}
  const links=url?buildShareUrls(title,url):null,showShare=Boolean(sharingEnabled&&url&&links);
  return <section className="post-engagement" aria-label="Post engagement"><div className="engagement-counts">{likesEnabled?<button className={liked?"post-like is-liked":"post-like"} type="button" aria-pressed={liked} aria-label={liked?"Unlike post":"Like post"} disabled={busy} onClick={()=>void toggle()}>{liked?"\u2665 Liked":"\u2661 Like"} {count}</button>:null}{commentsAvailable?<a href="#comments" className="comment-count-link" aria-label={`${commentCount} comments`}>{"\u25CF"} {commentCount} {commentCount===1?"Comment":"Comments"}</a>:null}</div>{showShare&&links?<div className="share-controls"><strong>Share</strong>{platforms.whatsapp?<a href={links.whatsapp} target="_blank" rel="noreferrer" aria-label="Share on WhatsApp">WhatsApp</a>:null}{platforms.facebook?<a href={links.facebook} target="_blank" rel="noreferrer" aria-label="Share on Facebook">Facebook</a>:null}{platforms.x?<a href={links.x} target="_blank" rel="noreferrer" aria-label="Share on X">X</a>:null}{platforms.linkedin?<a href={links.linkedin} target="_blank" rel="noreferrer" aria-label="Share on LinkedIn">LinkedIn</a>:null}{platforms.copyLink?<button type="button" onClick={()=>void copy()}>Copy Link</button>:null}{platforms.nativeShare&&native?<button type="button" onClick={()=>void nativeShare()}>Share...</button>:null}</div>:null}{feedback?<p className="share-feedback" role="status">{feedback}</p>:null}</section>;
}
