import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { canUsePermission } from "../src/auth/authorization";
import { defaultHomeConfig, homeConfigSchema, promoteDraft } from "../src/home-page/config";
assert(homeConfigSchema.safeParse(defaultHomeConfig).success);
assert(homeConfigSchema.safeParse({ ...defaultHomeConfig, sectionOrder: ["hero", "hero", "categoryDiscovery"] }).success === false);
for (const count of [0, 13, 2.5]) assert(!homeConfigSchema.safeParse({ ...defaultHomeConfig, latestStories: { ...defaultHomeConfig.latestStories, postCount: count } }).success);
for (const url of ["javascript:alert(1)", "//evil.example", "data:text/html,test"]) assert(!homeConfigSchema.safeParse({ ...defaultHomeConfig, hero: { ...defaultHomeConfig.hero, ctaDestination: url } }).success);
for (const url of ["/", "/blog"]) assert(homeConfigSchema.safeParse({ ...defaultHomeConfig, hero: { ...defaultHomeConfig.hero, ctaDestination: url } }).success);
const published = { ...defaultHomeConfig, hero: { ...defaultHomeConfig.hero, heading: "Published" } }; const draft = { ...published, hero: { ...published.hero, heading: "Draft" } };
assert.equal(promoteDraft(draft, published, false)?.hero.heading, "Published");
assert.equal(promoteDraft(draft, published, true)?.hero.heading, "Draft");
for (const section of ["hero", "latestStories", "categoryDiscovery"] as const) assert(homeConfigSchema.safeParse({ ...defaultHomeConfig, [section]: { ...defaultHomeConfig[section], visible: false } }).success);
const master = { isMasterAdmin: true, permissionKeys: new Set<string>() }; const viewer = { isMasterAdmin: false, permissionKeys: new Set(["pages.home.view"]) }; const editor = { isMasterAdmin: false, permissionKeys: new Set(["pages.home.view", "pages.home.edit"]) };
for (const permission of ["pages.home.view", "pages.home.edit", "pages.home.publish"]) assert(canUsePermission(master, permission));
assert(canUsePermission(viewer, "pages.home.view") && !canUsePermission(viewer, "pages.home.edit") && !canUsePermission(viewer, "pages.home.publish"));
assert(canUsePermission(editor, "pages.home.edit") && !canUsePermission(editor, "pages.home.publish"));
const actions = readFileSync(new URL("../app/(admin)/pages/home/actions.ts", import.meta.url), "utf8");
assert(actions.includes('.for("update")') && actions.includes("currentVersion !== id.data.expectedVersion"));
assert(actions.includes("page.home.draft_saved") && actions.includes("page.home.published"));
assert(actions.includes('id.data.intent === "publish" ? config.data : current.published'), "draft save must preserve Published");
const pageSource = readFileSync(new URL("../app/(admin)/pages/home/page.tsx", import.meta.url), "utf8");
assert(pageSource.includes("draft: homePageConfigurations.draft") && pageSource.includes("row?.draftVersion"), "saved Draft and version must reload into the editor");
const migration = readFileSync(new URL("../drizzle/0003_home_page_cms.sql", import.meta.url), "utf8"); assert(migration.includes('CREATE TABLE "home_page_configurations"'));
console.log("PASS: fallback defaults, draft/publish isolation, failed-publish preservation, visibility/order validation, post-count bounds, safe CTA, stale versioning, permissions, logging, and migration verified.");
