import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { notificationValues, visibleNotificationModules } from "../src/notifications/service";
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
const ordinary={isMasterAdmin:false,permissionKeys:new Set(["comments.view","notifications.view"])};
assert.deepEqual(visibleNotificationModules(ordinary),["comments"]);
assert.deepEqual(visibleNotificationModules({isMasterAdmin:true,permissionKeys:new Set()}),["contact","comments","subscribers","staff","blog","system"]);
const safe=notificationValues({type:"comment_reply_email_failed",module:"comments",title:" Reply failed\n",message:"password=secret-value operational summary",targetType:"comment",targetId:"123e4567-e89b-42d3-a456-426614174000",targetUrl:"/comments/123e4567-e89b-42d3-a456-426614174000"});
assert.equal(safe.message,"[redacted] operational summary");assert.equal(safe.dedupeKey,"comment_reply_email_failed:comment:123e4567-e89b-42d3-a456-426614174000");assert.equal(notificationValues({...safe,type:"comment_reply_email_failed",module:"comments",title:"x",message:"y",targetUrl:"https://external.test"}).targetUrl,undefined);
const schema=read("src/db/schema.ts"),migration=read("drizzle/0020_panoramic_miss_america.sql"),badges=read("src/notifications/badges.ts"),navigation=read("src/navigation/admin-navigation.ts"),subscriberActions=read("app/(admin)/subscribers/actions.ts"),publicSubscribe=read("../../app/api/subscribe/route.ts"),actions=read("app/(admin)/notifications/actions.ts"),detail=read("app/(admin)/notifications/[id]/page.tsx"),cleanup=read("scripts/cleanup-admin-notifications.ts"),cron=read("deployment/scheduled-publisher.cron"),comments=read("app/(admin)/comments/actions.ts"),staff=read("app/(admin)/staff/actions.ts"),worker=read("scripts/notify-subscribers.ts"),publisher=read("scripts/publish-scheduled-posts.ts"),contact=read("../../app/api/contact/route.ts");
for(const marker of ["adminNotifications","adminNotificationStatus","adminSeenAt","admin_notifications_unresolved_dedupe_uidx"])assert.ok(schema.includes(marker),marker);
for(const marker of ["notifications.view","notifications.manage","admin_seen_at","CURRENT_TIMESTAMP","admin_notifications_status_created_idx"])assert.ok(migration.includes(marker),marker);
assert.ok(badges.includes("status='new'")&&badges.includes("status='pending' AND deleted_at IS NULL")&&badges.includes("status='active' AND admin_seen_at IS NULL"));
assert.ok(navigation.includes('label: "Notifications"')&&navigation.includes("badgeLabel")&&navigation.includes('label: "Pending"'));
assert.ok(subscriberActions.includes("markNewSubscribersSeen")&&subscriberActions.includes("adminSeenAt: next === \"active\" ? null"));assert.ok(publicSubscribe.includes("admin_seen_at=CASE WHEN subscribers.status='unsubscribed' THEN NULL"));
assert.ok(actions.includes('status: "read"')&&!actions.includes('status: "resolved", readAt: null'));assert.ok(detail.includes("markNotificationRead")&&actions.includes("markAllNotificationsRead")&&actions.includes("resolveNotification"));
assert.ok(cleanup.includes("status='resolved'")&&cleanup.includes("interval '90 days'")&&cron.includes("cleanup:admin-notifications"));
for(const [source,marker] of [[comments,"comment_reply_email_failed"],[staff,"staff_invitation_email_failed"],[staff,"password_reset_email_failed"],[worker,"subscriber_job_failed"],[publisher,"scheduled_publishing_failed"],[contact,"recordContactEmailFailure"]])assert.ok(source.includes(marker),marker);
for(const source of [comments,staff,worker,publisher,contact])for(const forbidden of ["SMTP_APP_PASSWORD:","subscriber token secret","stack trace"])assert.ok(!source.toLowerCase().includes(forbidden.toLowerCase()));
console.log("Section badges, subscriber acknowledgment, operational failure hooks, visibility, status, deduplication, privacy, and retention regressions passed.");
