import { Pool } from "pg";
import { createOperationalNotificationSql } from "../src/notifications/service";
import { mailer, storyTemplate } from "../src/subscribers/email";
const BATCH=25;

async function main(){
  if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required");
  const pool=new Pool({connectionString:process.env.DATABASE_URL,max:1}),mail=mailer();
  try{
    await pool.query("BEGIN");
    const[s]=(await pool.query("SELECT * FROM subscriber_settings WHERE id='global' FOR UPDATE")).rows;
    if(s&&!s.automatic_post_emails_enabled)await pool.query("UPDATE subscriber_settings SET pending_automatic_post_id=NULL WHERE id='global'");
    if(s?.automatic_post_emails_enabled&&s.pending_automatic_post_id&&(!s.last_automatic_sent_at||Date.now()-new Date(s.last_automatic_sent_at).valueOf()>=86_400_000)){
      await pool.query("INSERT INTO subscriber_notification_jobs(post_id,type,status) SELECT $1,'automatic','pending' WHERE EXISTS(SELECT 1 FROM posts WHERE id=$1 AND status='published' AND deleted_at IS NULL)",[s.pending_automatic_post_id]);
      await pool.query("UPDATE subscriber_settings SET pending_automatic_post_id=NULL,last_automatic_sent_at=CURRENT_TIMESTAMP WHERE id='global'");
    }
    await pool.query("COMMIT");
    await pool.query("BEGIN");
    const invalid=(await pool.query("UPDATE subscriber_notification_jobs j SET status='failed',completed_at=CURRENT_TIMESTAMP WHERE j.status IN('pending','processing') AND NOT EXISTS(SELECT 1 FROM posts p WHERE p.id=j.post_id AND p.status='published' AND p.deleted_at IS NULL) RETURNING j.id,j.post_id")).rows;
    const job=(await pool.query("SELECT j.id,j.post_id FROM subscriber_notification_jobs j JOIN posts p ON p.id=j.post_id WHERE j.status IN ('pending','processing') AND p.status='published' AND p.deleted_at IS NULL ORDER BY CASE j.type WHEN 'manual' THEN 0 ELSE 1 END,j.created_at LIMIT 1 FOR UPDATE OF j SKIP LOCKED")).rows[0];
    if(!job){await pool.query("COMMIT");for(const failed of invalid)await createOperationalNotificationSql(pool,{type:"subscriber_job_failed",module:"subscribers",title:"Subscriber notification job failed",message:"A subscriber notification job could not run because its post is no longer publishable.",targetType:"subscriber_job",targetId:failed.id,targetUrl:"/subscribers",severity:"error"});return}
    await pool.query("INSERT INTO subscriber_post_deliveries(notification_job_id,subscriber_id,post_id) SELECT $1,s.id,$2 FROM subscribers s WHERE s.status='active' ON CONFLICT(notification_job_id,subscriber_id) DO NOTHING",[job.id,job.post_id]);
    await pool.query("UPDATE subscriber_post_deliveries d SET status='failed',attempted_at=CURRENT_TIMESTAMP FROM subscribers s WHERE d.notification_job_id=$1 AND d.subscriber_id=s.id AND d.status='pending' AND s.status<>'active'",[job.id]);
    await pool.query("UPDATE subscriber_notification_jobs SET status='processing',started_at=COALESCE(started_at,CURRENT_TIMESTAMP),recipient_count=(SELECT count(*) FROM subscriber_post_deliveries WHERE notification_job_id=$1) WHERE id=$1",[job.id]);
    const rows=(await pool.query("WITH claimed AS (SELECT d.id FROM subscriber_post_deliveries d JOIN subscribers s ON s.id=d.subscriber_id WHERE d.notification_job_id=$1 AND d.status='pending' AND s.status='active' ORDER BY d.id LIMIT $2 FOR UPDATE OF d SKIP LOCKED),marked AS (UPDATE subscriber_post_deliveries d SET status='processing',attempted_at=CURRENT_TIMESTAMP FROM claimed WHERE d.id=claimed.id RETURNING d.*) SELECT m.id,m.subscriber_id,s.email,p.title,p.short_description,p.slug,p.featured_image_path,p.published_at FROM marked m JOIN subscribers s ON s.id=m.subscriber_id JOIN posts p ON p.id=m.post_id",[job.id,BATCH])).rows;
    await pool.query("COMMIT");
    for(const row of rows){let sent=false;try{const template=storyTemplate({subscriberId:row.subscriber_id,email:row.email,title:row.title,description:row.short_description,slug:row.slug,featuredImagePath:row.featured_image_path,publishedAt:row.published_at},mail.origin,mail.secret);await mail.transport.sendMail({from:mail.from,to:row.email,subject:`New Eraasim story: ${row.title}`,html:template.html,text:template.text,headers:{"List-Unsubscribe":`<${template.unsubscribe}>`}});sent=true}catch{console.error("Subscriber notification delivery failed.")}await pool.query("UPDATE subscriber_post_deliveries SET status=$2::subscriber_delivery_status,sent_at=CASE WHEN $2::subscriber_delivery_status='sent'::subscriber_delivery_status THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=$1",[row.id,sent?"sent":"failed"]);if(sent)await pool.query("UPDATE subscribers SET last_notification_at=CURRENT_TIMESTAMP WHERE id=$1",[row.subscriber_id])}
    const summary=(await pool.query("UPDATE subscriber_notification_jobs j SET success_count=x.sent,failure_count=x.failed,status=CASE WHEN x.remaining=0 THEN 'completed'::subscriber_job_status ELSE 'processing'::subscriber_job_status END,completed_at=CASE WHEN x.remaining=0 THEN CURRENT_TIMESTAMP ELSE NULL END FROM (SELECT count(*) FILTER(WHERE status='sent')::int sent,count(*) FILTER(WHERE status='failed')::int failed,count(*) FILTER(WHERE status IN('pending','processing'))::int remaining FROM subscriber_post_deliveries WHERE notification_job_id=$1)x WHERE j.id=$1 RETURNING j.success_count,j.failure_count,j.status",[job.id])).rows[0];
    if(summary?.failure_count>0&&summary.status==="completed")await createOperationalNotificationSql(pool,{type:"subscriber_job_failed",module:"subscribers",title:"Subscriber deliveries failed",message:`Subscriber notification job completed with ${summary.failure_count} failed and ${summary.success_count} successful deliveries.`,targetType:"subscriber_job",targetId:job.id,targetUrl:"/subscribers",severity:"error"});
    for(const failed of invalid)await createOperationalNotificationSql(pool,{type:"subscriber_job_failed",module:"subscribers",title:"Subscriber notification job failed",message:"A subscriber notification job could not run because its post is no longer publishable.",targetType:"subscriber_job",targetId:failed.id,targetUrl:"/subscribers",severity:"error"});
  }catch(error){try{await pool.query("ROLLBACK")}catch{}await createOperationalNotificationSql(pool,{type:"subscriber_worker_failed",module:"system",title:"Subscriber worker failed",message:"The automatic subscriber notification worker could not complete. Review worker health and retry safely.",severity:"error",dedupeKey:"subscriber_worker_failed:system"});throw error}finally{await pool.end()}
}
main().catch(error=>{console.error("Subscriber notification worker failed.",error instanceof Error?error.message:"Unknown");process.exitCode=1});
