import Link from "next/link";
import { asc } from "drizzle-orm";
import { changeStaffStatus, resendInvitation, revokeInvitation } from "@/app/(admin)/staff/actions";
import { canUsePermission, requirePermission } from "@/src/auth/authorization";
import { db } from "@/src/db";
import { staffAccounts } from "@/src/db/schema";
const fmt=new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"});
export default async function StaffList(){
  const{authorization}=await requirePermission("staff.view");const rows=await db.select().from(staffAccounts).orderBy(asc(staffAccounts.isMasterAdmin),asc(staffAccounts.email));
  return <section className="staff-list"><div className="list-page-header"><div><p className="page-eyebrow">Staff</p><h1>All Staff</h1><p>Roles are labels only. Access is granted directly through each staff member&apos;s permission matrix.</p></div>{canUsePermission(authorization,"staff.create")?<Link className="new-post-link" href="/staff/new">New Staff</Link>:null}</div><div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Last Login</th><th>Created</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.name??"Not registered"}{row.isMasterAdmin?<small>Master Admin</small>:null}</td><td className="staff-email">{row.email}</td><td>{row.roleLabel??"—"}</td><td><span className={`staff-status staff-status-${row.status}`}>{row.status[0].toUpperCase()+row.status.slice(1)}</span></td><td>{row.lastLoginAt?<time dateTime={row.lastLoginAt.toISOString()}>{fmt.format(row.lastLoginAt)}</time>:"—"}</td><td><time dateTime={row.createdAt.toISOString()}>{fmt.format(row.createdAt)}</time></td><td className="staff-actions"><Link href={`/staff/${row.id}`}>View</Link>{!row.isMasterAdmin&&canUsePermission(authorization,"staff.permissions")&&row.status!=="invited"?<Link href={`/staff/${row.id}/permissions`}>Permissions</Link>:null}{!row.isMasterAdmin&&row.status==="invited"&&canUsePermission(authorization,"staff.create")?<form action={resendInvitation}><input type="hidden" name="staffId" value={row.id}/><button>Resend Invitation</button></form>:null}{!row.isMasterAdmin&&row.status==="invited"&&canUsePermission(authorization,"staff.manage")?<form action={revokeInvitation}><input type="hidden" name="staffId" value={row.id}/><button>Revoke Invitation</button></form>:null}{!row.isMasterAdmin&&row.status==="active"&&canUsePermission(authorization,"staff.manage")?<form action={changeStaffStatus}><input type="hidden" name="staffId" value={row.id}/><button name="action" value="disable">Disable</button></form>:null}{!row.isMasterAdmin&&row.status==="disabled"&&canUsePermission(authorization,"staff.manage")?<form action={changeStaffStatus}><input type="hidden" name="staffId" value={row.id}/><button name="action" value="enable">Re-enable</button></form>:null}</td></tr>)}</tbody></table></div></section>;
}
