import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { acceptContactRate, defaultContactConfig, parsePublicContact, validateContactInput } from "../src/contact-page";
const valid = { name: " A ", email: "A@example.com", phone: "", subject: "Hello", message: "Plain text" };
assert.deepEqual(validateContactInput(valid), { name: "A", email: "a@example.com", phone: null, subject: "Hello", message: "Plain text" });
assert.equal(validateContactInput({ ...valid, email: "bad" }), null); assert.equal(validateContactInput({ ...valid, message: "<script>x</script>" }), null); assert.equal(validateContactInput({ ...valid, name: "x".repeat(121) }), null); assert.equal(parsePublicContact(null).form.visible, false);
const key = `regression-${Date.now()}`; for (let index = 0; index < 5; index++) assert.equal(acceptContactRate(key, 1), true); assert.equal(acceptContactRate(key, 1), false); assert.equal(acceptContactRate(key, 700_001), true); assert.equal(defaultContactConfig.form.successMessage.length > 0, true);
const component = readFileSync(new URL("../components/contact-form.tsx", import.meta.url), "utf8"); const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");
assert.match(component, /<RequiredLabel>Name<\/RequiredLabel>/); assert.match(component, /aria-hidden="true">\*<\/span>/); assert.match(component, /className="visually-hidden"> required/); assert.match(component, /<label><RequiredLabel>/); assert.doesNotMatch(component, /position:\s*absolute/); assert.match(css, /\.contact-label-text\{display:inline/); assert.match(css, /@media\(max-width:760px\)/);
console.log("Contact form regression passed.");
