import{cache}from"react";import{getPool}from"@/src/db";import{PUBLIC_POST_SQL,type PublicPostCard}from"@/src/public-blog";
export type BlogPageConfig={general:{heading:string;intro:string;seoTitle:string;seoDescription:string};pinned:{visible:boolean;postIds:string[]};feed:{latestVisible:boolean;visible:boolean;postsPerPage:number};sidebar:{visible:boolean;categoriesVisible:boolean;trendingVisible:boolean;trendingCount:number;archiveVisible:boolean}};
export const defaultBlogPageConfig:BlogPageConfig={general:{heading:"Blog",intro:"Thoughtful notes on culture, food, places and the experiences that connect them.",seoTitle:"Blog | Eraasim",seoDescription:"Published stories of culture, food and places from Eraasim."},pinned:{visible:true,postIds:[]},feed:{latestVisible:true,visible:true,postsPerPage:5},sidebar:{visible:true,categoriesVisible:true,trendingVisible:true,trendingCount:10,archiveVisible:true}};
const hexUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,keys=(value:unknown)=>value&&typeof value==="object"?value as Record<string,unknown>:{};
export function parsePublishedBlogPage(value:unknown):BlogPageConfig{const v=keys(value),g=keys(v.general),p=keys(v.pinned),f=keys(v.feed),s=keys(v.sidebar),ids=Array.isArray(p.postIds)?p.postIds:[];const strings=[g.heading,g.intro,g.seoTitle,g.seoDescription],booleans=[p.visible,f.latestVisible,f.visible,s.visible,s.categoriesVisible,s.trendingVisible,s.archiveVisible];return strings.every(x=>typeof x==="string")&&typeof g.heading==="string"&&g.heading.trim().length>0&&g.heading.length<=200&&String(g.intro).length<=1000&&String(g.seoTitle).length<=200&&String(g.seoDescription).length<=500&&ids.length<=3&&ids.every(id=>typeof id==="string"&&hexUuid.test(id))&&new Set(ids).size===ids.length&&booleans.every(x=>typeof x==="boolean")&&Number.isInteger(f.postsPerPage)&&Number(f.postsPerPage)>=3&&Number(f.postsPerPage)<=20&&Number.isInteger(s.trendingCount)&&Number(s.trendingCount)>=5&&Number(s.trendingCount)<=20?v as BlogPageConfig:defaultBlogPageConfig}
export const parseBlogPageNumber=(value:string|undefined)=>{const page=Number(value);return Number.isSafeInteger(page)&&page>0?page:1};
const columns=`p.id,p.slug,p.title,p.short_description AS "shortDescription",p.featured_image_path AS "featuredImagePath",c.name AS "categoryName",c.slug AS "categorySlug",p.published_at AS "publishedAt",staff.name AS "authorName",p.content`;
const joins="LEFT JOIN categories c ON c.id=p.category_id INNER JOIN staff_accounts staff ON staff.id=p.created_by_id";
export type SidebarPost={id:string;slug:string;title:string;categoryId:string|null;categoryName:string|null;categorySlug:string|null;parentId:string|null;publishedAt:Date};export type SidebarCategory={id:string;name:string;slug:string;parentId:string|null};export type TrendingPost={slug:string;title:string;categoryName:string|null;categorySlug:string|null;publishedAt:Date;views:number};
export const getPublishedBlogConfig=cache(async()=>{const pool=getPool();try{const result=await pool.query<{published:unknown}>("SELECT published FROM blog_page_configurations WHERE id='blog' LIMIT 1");return parsePublishedBlogPage(result.rows[0]?.published)}catch(error){if((error as{code?:string}).code==="42P01")return defaultBlogPageConfig;throw error}});
export async function getBlogPageData(config:BlogPageConfig,requestedPage:number){const pool=getPool(),pinnedIds=config.pinned.visible?config.pinned.postIds:[];const count=await pool.query<{total:number}>(`SELECT count(*)::int total FROM posts p WHERE ${PUBLIC_POST_SQL} AND NOT(p.id=ANY($1::uuid[]))`,[pinnedIds]);const total=count.rows[0]?.total??0,totalPages=Math.max(1,Math.ceil(total/config.feed.postsPerPage)),page=Math.min(requestedPage,totalPages);const [pinned,feed,categories,sidebarPosts,trending]=await Promise.all([page===1&&pinnedIds.length?pool.query<PublicPostCard>(`SELECT ${columns} FROM posts p ${joins} WHERE ${PUBLIC_POST_SQL} AND p.id=ANY($1::uuid[]) ORDER BY array_position($1::uuid[],p.id) LIMIT 3`,[pinnedIds]):Promise.resolve({rows:[]} as{rows:PublicPostCard[]}),pool.query<PublicPostCard>(`SELECT ${columns} FROM posts p ${joins} WHERE ${PUBLIC_POST_SQL} AND NOT(p.id=ANY($1::uuid[])) ORDER BY p.published_at DESC,p.id DESC LIMIT $2 OFFSET $3`,[pinnedIds,config.feed.postsPerPage,(page-1)*config.feed.postsPerPage]),config.sidebar.visible&&config.sidebar.categoriesVisible?pool.query<SidebarCategory>(`SELECT id,name,slug,parent_id AS "parentId" FROM categories ORDER BY lower(name),id LIMIT 250`):Promise.resolve({rows:[]} as{rows:SidebarCategory[]}),config.sidebar.visible&&(config.sidebar.categoriesVisible||config.sidebar.archiveVisible)?pool.query<SidebarPost>(`SELECT p.id,p.slug,p.title,p.category_id AS "categoryId",c.name AS "categoryName",c.slug AS "categorySlug",c.parent_id AS "parentId",p.published_at AS "publishedAt" FROM posts p LEFT JOIN categories c ON c.id=p.category_id WHERE ${PUBLIC_POST_SQL} ORDER BY p.published_at DESC,p.id DESC LIMIT 500`):Promise.resolve({rows:[]} as{rows:SidebarPost[]}),config.sidebar.visible&&config.sidebar.trendingVisible?pool.query<TrendingPost>(`SELECT p.slug,p.title,c.name AS "categoryName",c.slug AS "categorySlug",p.published_at AS "publishedAt",COALESCE(sum(v.view_count),0)::int views FROM posts p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN post_daily_views v ON v.post_id=p.id AND v.view_date BETWEEN ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date-29) AND (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date WHERE ${PUBLIC_POST_SQL} GROUP BY p.id,c.name,c.slug ORDER BY views DESC,p.published_at DESC,p.id DESC LIMIT $1`,[config.sidebar.trendingCount]):Promise.resolve({rows:[]} as{rows:TrendingPost[]})]);return{pinned:pinned.rows,feed:feed.rows,page,total,totalPages,categories:categories.rows,sidebarPosts:sidebarPosts.rows,trending:trending.rows}}
