import { createHash } from "node:crypto";
import { getPool } from "@/src/db";

export type CommentsSettings={enabled:boolean;autoApprove:boolean;initialCount:number;loadMoreCount:number;pendingMessage:string;approvedMessage:string};
export const defaultCommentsSettings:CommentsSettings={enabled:true,autoApprove:false,initialCount:10,loadMoreCount:10,pendingMessage:"Your comment has been submitted for review.",approvedMessage:"Your comment has been published."};
export function parseCommentsSettings(value:unknown):CommentsSettings{if(!value||typeof value!=="object")return defaultCommentsSettings;const v=value as CommentsSettings;if(typeof v.enabled!=="boolean"||typeof v.autoApprove!=="boolean"||!Number.isInteger(v.initialCount)||v.initialCount<5||v.initialCount>50||!Number.isInteger(v.loadMoreCount)||v.loadMoreCount<5||v.loadMoreCount>50||typeof v.pendingMessage!=="string"||!v.pendingMessage.trim()||v.pendingMessage.length>500||typeof v.approvedMessage!=="string"||!v.approvedMessage.trim()||v.approvedMessage.length>500)return defaultCommentsSettings;return v}
export async function getCommentsSettings(){try{const r=await getPool().query<CommentsSettings>('SELECT enabled,auto_approve AS "autoApprove",initial_count AS "initialCount",load_more_count AS "loadMoreCount",pending_message AS "pendingMessage",approved_message AS "approvedMessage" FROM comments_settings WHERE id=\'global\' LIMIT 1');return parseCommentsSettings(r.rows[0])}catch(e){if((e as{code?:string}).code==="42P01")return{...defaultCommentsSettings,enabled:false};throw e}}
export type PublicComment={id:string;name:string;comment:string;createdAt:Date;likes:number;replies:{id:string;name:string;comment:string;createdAt:Date}[]};
export async function getPublicComments(postId:string,limit:number,cursor?:string){const pool=getPool(),safe=Math.min(50,Math.max(5,limit)),parts=cursor?.split("_")??[],cursorDate=parts[0]?new Date(parts[0]):null,cursorId=parts[1];const params:unknown[]=[postId,safe+1],clause=cursorDate&&!Number.isNaN(cursorDate.valueOf())&&/^[0-9a-f-]{36}$/i.test(cursorId??"")?" AND (c.created_at,c.id)>($3::timestamptz,$4::uuid)":"",values=clause?[...params,cursorDate,cursorId]:params;const rows=await pool.query<Omit<PublicComment,"replies">>(`SELECT c.id,c.name,c.comment,c.created_at AS "createdAt",count(l.id)::int AS likes FROM blog_comments c LEFT JOIN comment_likes l ON l.comment_id=c.id WHERE c.post_id=$1 AND c.parent_comment_id IS NULL AND c.is_admin_reply=false AND c.status='approved' AND c.deleted_at IS NULL${clause} GROUP BY c.id ORDER BY c.created_at,c.id LIMIT $2`,values),visible=rows.rows.slice(0,safe),ids=visible.map(c=>c.id),replies=ids.length?await pool.query<{id:string;parentCommentId:string;name:string;comment:string;createdAt:Date}>(`SELECT id,parent_comment_id AS "parentCommentId",name,comment,created_at AS "createdAt" FROM blog_comments WHERE parent_comment_id=ANY($1::uuid[]) AND is_admin_reply=true AND status='approved' AND deleted_at IS NULL ORDER BY created_at,id`,[ids]):{rows:[]};const items=visible.map(c=>({...c,replies:replies.rows.filter(r=>r.parentCommentId===c.id)})),last=items.at(-1);return{items,hasMore:rows.rows.length>safe,nextCursor:last?`${new Date(last.createdAt).toISOString()}_${last.id}`:null}}
export async function getApprovedCommentCount(postId:string){const r=await getPool().query<{count:number}>("SELECT count(*)::int AS count FROM blog_comments WHERE post_id=$1 AND parent_comment_id IS NULL AND is_admin_reply=false AND status='approved' AND deleted_at IS NULL",[postId]);return r.rows[0]?.count??0}
export function validateCommentInput(value:unknown){if(!value||typeof value!=="object")return null;const v=value as Record<string,unknown>,name=typeof v.name==="string"?v.name.trim():"",email=typeof v.email==="string"?v.email.trim().toLowerCase():"",comment=typeof v.comment==="string"?v.comment.trim():"";if(!name||name.length>120||!email||email.length>254||!/^\S+@\S+\.\S+$/.test(email)||!comment||comment.length>5000||/[<>]/.test(comment))return null;return{name,email,comment}}
const attempts=new Map<string,{count:number;expires:number}>();export function acceptCommentRate(identity:string,now=Date.now()){const key=createHash("sha256").update(identity).digest("hex"),old=attempts.get(key);if(attempts.size>2000)for(const[k,v]of attempts)if(v.expires<=now)attempts.delete(k);if(!old||old.expires<=now){attempts.set(key,{count:1,expires:now+60_000});return true}if(old.count>=3)return false;old.count++;return true}
export function hashAnonymousToken(token:string){return createHash("sha256").update(token).digest("hex")}
