import { getPool } from "@/src/db";

export type EngagementPlatforms={whatsapp:boolean;facebook:boolean;x:boolean;linkedin:boolean;copyLink:boolean;nativeShare:boolean};
export type PublicPostEngagement={likesEnabled:boolean;sharingEnabled:boolean;likeCount:number;commentCount:number;platforms:EngagementPlatforms};
const defaults:PublicPostEngagement={likesEnabled:true,sharingEnabled:true,likeCount:0,commentCount:0,platforms:{whatsapp:true,facebook:true,x:true,linkedin:true,copyLink:true,nativeShare:true}};
export function canonicalBlogUrl(slug:string,environment:Record<string,string|undefined>=process.env){try{const site=new URL(environment.PUBLIC_SITE_URL??"");if(!["https:","http:"].includes(site.protocol)||site.username||site.password)return null;return `${site.origin}/blog/${encodeURIComponent(slug)}`}catch{return null}}
export async function getPublicPostEngagement(postId:string):Promise<PublicPostEngagement>{
  const pool=getPool();
  try{const result=await pool.query<{likesEnabled:boolean;sharingEnabled:boolean;likeCount:number;commentCount:number;whatsapp:boolean;facebook:boolean;x:boolean;linkedin:boolean;copyLink:boolean;nativeShare:boolean}>(`SELECT p.likes_enabled AND COALESCE(s.likes_enabled,true) AS "likesEnabled",p.sharing_enabled AND COALESCE(s.sharing_enabled,true) AS "sharingEnabled",(SELECT count(*)::int FROM post_likes l WHERE l.post_id=p.id) AS "likeCount",(SELECT count(*)::int FROM blog_comments c WHERE c.post_id=p.id AND c.parent_comment_id IS NULL AND c.is_admin_reply=false AND c.status='approved' AND c.deleted_at IS NULL) AS "commentCount",COALESCE(s.whatsapp_enabled,true) AS whatsapp,COALESCE(s.facebook_enabled,true) AS facebook,COALESCE(s.x_enabled,true) AS x,COALESCE(s.linkedin_enabled,true) AS linkedin,COALESCE(s.copy_link_enabled,true) AS "copyLink",COALESCE(s.native_share_enabled,true) AS "nativeShare" FROM posts p LEFT JOIN blog_engagement_settings s ON s.id='global' WHERE p.id=$1 AND p.status='published' AND p.deleted_at IS NULL LIMIT 1`,[postId]);const row=result.rows[0];return row?{likesEnabled:row.likesEnabled,sharingEnabled:row.sharingEnabled,likeCount:row.likesEnabled?row.likeCount:0,commentCount:row.commentCount,platforms:{whatsapp:row.whatsapp,facebook:row.facebook,x:row.x,linkedin:row.linkedin,copyLink:row.copyLink,nativeShare:row.nativeShare}}:{...defaults,likesEnabled:false,sharingEnabled:false}}
  catch(error){if(["42P01","42703"].includes((error as{code?:string}).code??"")){const legacy=await pool.query<{commentCount:number}>("SELECT count(*)::int AS \"commentCount\" FROM blog_comments WHERE post_id=$1 AND parent_comment_id IS NULL AND is_admin_reply=false AND status='approved' AND deleted_at IS NULL",[postId]);return{...defaults,likeCount:0,commentCount:legacy.rows[0]?.commentCount??0}}throw error}
}
