import { getPool } from "@/src/db";
export const socialPlatforms = ["facebook", "instagram", "youtube", "x", "linkedin"] as const;
export type FooterConfig = { categoryDirectory: { visible: boolean; heading: string }; content: { heading: string; description: string }; pageLinks: { pageId: string; visible: boolean; order: number }[]; socialLinks: { platform: typeof socialPlatforms[number]; url: string; visible: boolean }[]; legacyNavigation?: boolean };
export type FooterCategory = { id: string; name: string; slug: string; parentId: string | null };
export type FooterPage = { id: string; title: string; path: string };
export const defaultFooterConfig: FooterConfig = { categoryDirectory: { visible: false, heading: "Explore Categories" }, content: { heading: "Eraasim", description: "Stories of culture, food and places—gathered with curiosity and care." }, pageLinks: [], socialLinks: socialPlatforms.map((platform) => ({ platform, url: "", visible: false })), legacyNavigation: true };
const safeHttps = (value: string) => { try { return new URL(value).protocol === "https:"; } catch { return false; } };
export function parsePublicFooter(value: unknown): FooterConfig { if (!value || typeof value !== "object") return defaultFooterConfig; const config = value as FooterConfig; if (!config.categoryDirectory || typeof config.categoryDirectory.heading !== "string" || !config.content || typeof config.content.heading !== "string" || typeof config.content.description !== "string" || !Array.isArray(config.pageLinks) || !Array.isArray(config.socialLinks) || config.socialLinks.some((link) => !socialPlatforms.includes(link.platform) || typeof link.url !== "string" || (link.visible && !safeHttps(link.url)))) return defaultFooterConfig; return config; }
export async function getPublicFooter() { const pool = getPool(); try { const [footer, categories] = await Promise.all([pool.query<{ published: unknown }>("SELECT published FROM footer_configurations WHERE id = 'footer' LIMIT 1"), pool.query<FooterCategory>("SELECT id, name, slug, parent_id AS \"parentId\" FROM categories ORDER BY lower(name), id LIMIT 500")]); const pages: FooterPage[] = []; return { config: parsePublicFooter(footer.rows[0]?.published), categories: categories.rows, pages }; } catch (error) { if ((error as { code?: string }).code === "42P01") return { config: defaultFooterConfig, categories: [], pages: [] }; throw error; } }
