import { getPool } from "@/src/db";
import { publicMediaUrl } from "@/src/media";

export const HOME_SECTION_IDS = ["hero", "latestStories", "categoryDiscovery"] as const;
export type HomeConfig = { seoTitle?: string; seoDescription?: string; hero: { visible: boolean; backgroundImagePath: string; showBackgroundImage: boolean; backgroundImageOpacity: number; profileImagePath: string; showProfileImage: boolean; profileImageOpacity: number; eyebrow: string; showEyebrow: boolean; eyebrowSize: number; heading: string; showHeading: boolean; headingSize: number; description: string; showDescription: boolean; descriptionSize: number; ctaLabel: string; showCta: boolean; ctaDestination: "/" | "/blog" }; latestStories: { visible: boolean; heading: string; description: string; postCount: number }; categoryDiscovery: { visible: boolean; heading: string; description: string }; sectionOrder: (typeof HOME_SECTION_IDS)[number][] };
export type ResolvedHomeConfig = HomeConfig & { useLegacyHeroMark: boolean };
export const defaultHomeConfig: HomeConfig = { seoTitle: "", seoDescription: "", hero: { visible: true, backgroundImagePath: "", showBackgroundImage: false, backgroundImageOpacity: 100, profileImagePath: "", showProfileImage: false, profileImageOpacity: 100, eyebrow: "Culture · Food · Places", showEyebrow: true, eyebrowSize: 11, heading: "Stories rooted in people and place.", showHeading: true, headingSize: 96, description: "Eraasim is a journal for thoughtful encounters, lived experiences and the details that make a place memorable.", showDescription: true, descriptionSize: 22, ctaLabel: "Explore the journal", showCta: true, ctaDestination: "/blog" }, latestStories: { visible: true, heading: "Latest stories", description: "Freshly published journeys, observations and reflections.", postCount: 6 }, categoryDiscovery: { visible: true, heading: "Explore by category", description: "Follow a broad theme or step into one of its more specific paths." }, sectionOrder: [...HOME_SECTION_IDS] };
function boundedNumber(value: unknown, min: number, max: number, fallback: number) { return typeof value === "number" && Number.isInteger(value) && value >= min && value <= max ? value : fallback; }
function imagePath(value: unknown) { return typeof value === "string" && publicMediaUrl(value) ? value : ""; }
function normalize(value: unknown): HomeConfig | null {
  if (!value || typeof value !== "object") return null;
  const v = value as Record<string, unknown>; const hero = v.hero as Record<string, unknown> | undefined; const latest = v.latestStories as Record<string, unknown> | undefined; const category = v.categoryDiscovery as Record<string, unknown> | undefined;
  if (!hero || !latest || !category || typeof hero.visible !== "boolean" || typeof hero.eyebrow !== "string" || typeof hero.heading !== "string" || typeof hero.description !== "string" || typeof hero.ctaLabel !== "string" || !["/", "/blog"].includes(String(hero.ctaDestination)) || typeof latest.visible !== "boolean" || typeof latest.heading !== "string" || typeof latest.description !== "string" || !Number.isInteger(latest.postCount) || Number(latest.postCount) < 1 || Number(latest.postCount) > 12 || typeof category.visible !== "boolean" || typeof category.heading !== "string" || typeof category.description !== "string" || !Array.isArray(v.sectionOrder) || v.sectionOrder.length !== 3 || new Set(v.sectionOrder).size !== 3 || !v.sectionOrder.every((id) => HOME_SECTION_IDS.includes(id as (typeof HOME_SECTION_IDS)[number]))) return null;
  return { seoTitle: typeof v.seoTitle === "string" ? v.seoTitle : "", seoDescription: typeof v.seoDescription === "string" ? v.seoDescription : "", hero: { visible: hero.visible, backgroundImagePath: imagePath(hero.backgroundImagePath), showBackgroundImage: hero.showBackgroundImage === true, backgroundImageOpacity: boundedNumber(hero.backgroundImageOpacity, 0, 100, 100), profileImagePath: imagePath(hero.profileImagePath), showProfileImage: hero.showProfileImage === true, profileImageOpacity: boundedNumber(hero.profileImageOpacity, 0, 100, 100), eyebrow: hero.eyebrow, showEyebrow: hero.showEyebrow !== false, eyebrowSize: boundedNumber(hero.eyebrowSize, 10, 40, 11), heading: hero.heading, showHeading: hero.showHeading !== false, headingSize: boundedNumber(hero.headingSize, 20, 100, 96), description: hero.description, showDescription: hero.showDescription !== false, descriptionSize: boundedNumber(hero.descriptionSize, 12, 48, 22), ctaLabel: hero.ctaLabel, showCta: hero.showCta !== false, ctaDestination: hero.ctaDestination as "/" | "/blog" }, latestStories: latest as HomeConfig["latestStories"], categoryDiscovery: category as HomeConfig["categoryDiscovery"], sectionOrder: v.sectionOrder as HomeConfig["sectionOrder"] };
}
export function resolvePublishedHome(value: unknown, useLegacyHeroMark = false): ResolvedHomeConfig { return { ...(normalize(value) ?? defaultHomeConfig), useLegacyHeroMark }; }
export async function getPublishedHomeConfig() { const result = await getPool().query<{ published: unknown }>("SELECT published FROM home_page_configurations WHERE id = 'home' LIMIT 1"); const published = result.rows[0]?.published; return resolvePublishedHome(published, published == null); }
