import { getPool } from "@/src/db";
import { publicMediaUrl } from "@/src/media";

export const HOME_SECTION_IDS = ["hero", "featuredStory", "latestStories"] as const;
type Hero = { visible: boolean; backgroundImagePath: string; showBackgroundImage: boolean; backgroundImageOpacity: number; profileImagePath: string; showProfileImage: boolean; profileImageOpacity: number; eyebrow: string; showEyebrow: boolean; eyebrowSize: number; heading: string; showHeading: boolean; headingSize: number; description: string; showDescription: boolean; descriptionSize: number; ctaLabel: string; showCta: boolean; ctaDestination: "/" | "/blog" };
export type HomeConfig = { seoTitle?: string; seoDescription?: string; hero: Hero; featuredStory: { visible: boolean; sourceMode: "latest" | "manual"; selectedPostId: string | null }; latestStories: { visible: boolean; heading: string; description: string; selectionMode: "automatic" | "manual"; manualPostIds: string[]; rotationSeconds: number }; sectionOrder: (typeof HOME_SECTION_IDS)[number][] };
export type ResolvedHomeConfig = HomeConfig & { useLegacyHeroMark: boolean };
export const defaultHomeConfig: HomeConfig = { seoTitle: "", seoDescription: "", hero: { visible: true, backgroundImagePath: "", showBackgroundImage: false, backgroundImageOpacity: 100, profileImagePath: "", showProfileImage: false, profileImageOpacity: 100, eyebrow: "Culture · Food · Places", showEyebrow: true, eyebrowSize: 11, heading: "Stories rooted in people and place.", showHeading: true, headingSize: 96, description: "Eraasim is a journal for thoughtful encounters, lived experiences and the details that make a place memorable.", showDescription: true, descriptionSize: 22, ctaLabel: "Explore the journal", showCta: true, ctaDestination: "/blog" }, featuredStory: { visible: true, sourceMode: "latest", selectedPostId: null }, latestStories: { visible: true, heading: "Latest & Trending Stories", description: "Freshly published and most-read stories from the journal.", selectionMode: "automatic", manualPostIds: [], rotationSeconds: 18 }, sectionOrder: [...HOME_SECTION_IDS] };
function bounded(value: unknown, min: number, max: number, fallback: number) { return typeof value === "number" && Number.isInteger(value) && value >= min && value <= max ? value : fallback; }
function path(value: unknown) { return typeof value === "string" && publicMediaUrl(value) ? value : ""; }
function uuid(value: unknown) { return typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value) ? value : null; }
function normalize(value: unknown): HomeConfig | null {
  if (!value || typeof value !== "object") return null; const v = value as Record<string, unknown>; const h = v.hero as Record<string, unknown> | undefined; const l = v.latestStories as Record<string, unknown> | undefined; const f = v.featuredStory as Record<string, unknown> | undefined;
  if (!h || !l || typeof h.visible !== "boolean" || typeof h.eyebrow !== "string" || typeof h.heading !== "string" || typeof h.description !== "string" || typeof h.ctaLabel !== "string" || !["/", "/blog"].includes(String(h.ctaDestination)) || typeof l.visible !== "boolean" || typeof l.heading !== "string" || typeof l.description !== "string") return null;
  const hero: Hero = { visible: h.visible, backgroundImagePath: path(h.backgroundImagePath), showBackgroundImage: h.showBackgroundImage === true, backgroundImageOpacity: bounded(h.backgroundImageOpacity, 0, 200, 100), profileImagePath: path(h.profileImagePath), showProfileImage: h.showProfileImage === true, profileImageOpacity: bounded(h.profileImageOpacity, 0, 100, 100), eyebrow: h.eyebrow, showEyebrow: h.showEyebrow !== false, eyebrowSize: bounded(h.eyebrowSize, 10, 40, 11), heading: h.heading, showHeading: h.showHeading !== false, headingSize: bounded(h.headingSize, 20, 100, 96), description: h.description, showDescription: h.showDescription !== false, descriptionSize: bounded(h.descriptionSize, 12, 48, 22), ctaLabel: h.ctaLabel, showCta: h.showCta !== false, ctaDestination: h.ctaDestination as "/" | "/blog" };
  const ids = Array.isArray(l.manualPostIds) ? l.manualPostIds.map(uuid).filter((id): id is string => Boolean(id)).slice(0, 9) : [];
  const oldOrder = Array.isArray(v.sectionOrder) ? v.sectionOrder : [];
  return { seoTitle: typeof v.seoTitle === "string" ? v.seoTitle : "", seoDescription: typeof v.seoDescription === "string" ? v.seoDescription : "", hero, featuredStory: { visible: typeof f?.visible === "boolean" ? f.visible : true, sourceMode: f?.sourceMode === "manual" ? "manual" : "latest", selectedPostId: uuid(f?.selectedPostId) }, latestStories: { visible: l.visible, heading: l.heading === "Latest stories" ? defaultHomeConfig.latestStories.heading : l.heading, description: l.description, selectionMode: l.selectionMode === "manual" ? "manual" : "automatic", manualPostIds: [...new Set(ids)], rotationSeconds: bounded(l.rotationSeconds, 10, 60, 18) }, sectionOrder: oldOrder.includes("featuredStory") ? oldOrder.filter((id): id is HomeConfig["sectionOrder"][number] => HOME_SECTION_IDS.includes(id as HomeConfig["sectionOrder"][number])) : [...HOME_SECTION_IDS] };
}
export function resolvePublishedHome(value: unknown, useLegacyHeroMark = false): ResolvedHomeConfig { return { ...(normalize(value) ?? defaultHomeConfig), useLegacyHeroMark }; }
export async function getPublishedHomeConfig() { const result = await getPool().query<{ published: unknown }>("SELECT published FROM home_page_configurations WHERE id = 'home' LIMIT 1"); const published = result.rows[0]?.published; return resolvePublishedHome(published, published == null); }
